"""
This type stub file was generated by pyright.
"""

__all__ = ["__version__", "__version_tuple__", "version", "version_tuple"]
VERSION_TUPLE = tuple[int, int, int]
version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE
