"""
This type stub file was generated by pyright.
"""

import enum
from typing import Any, Dict, TypeVar

import attr
from labgrid import Target

@attr.s(eq=False)
class StateError(Exception):
    msg = ...

@attr.s(eq=False)
class BindingError(Exception):
    msg = ...

@enum.unique
class BindingState(enum.Enum):
    error = ...
    idle = ...
    bound = ...
    active = ...

_TFunc = TypeVar("_TFunc")

@attr.s(eq=False)
class BindingMixin:
    """
    Handles the binding and activation of drivers and their supplying resources
    and drivers.

    One client can be bound to many suppliers, and one supplier can be bound by
    many clients.

    Conflicting access to one supplier can be avoided by deactivating
    conflicting clients before activation (using the resolve_conflicts
    callback).
    """

    bindings: Dict[str, Any] = ...
    target: Target = ...
    name: str = ...
    state = ...
    def __attrs_post_init__(self) -> None: ...
    @property
    def display_name(self) -> str: ...
    def on_supplier_bound(self, supplier) -> None:
        """Called by the Target after a new supplier has been bound"""
        ...

    def on_client_bound(self, client) -> None:
        """Called by the Target after a new client has been bound"""
        ...

    def on_activate(self) -> None:
        """Called by the Target when this object has been activated"""
        ...

    def on_deactivate(self) -> None:
        """Called by the Target when this object has been deactivated"""
        ...

    def resolve_conflicts(self, client) -> None:
        """
        Called by the Target to allow this object to deactivate conflicting
        clients.
        """
        ...

    def get_bound_resources(self):
        """
        Called by the Target to find the correct driver corresponding to a resource
        """
        ...

    @classmethod
    def check_active(cls, func: _TFunc) -> _TFunc: ...
    @classmethod
    def check_bound(cls, func: _TFunc) -> _TFunc: ...

    class NamedBinding:
        """
        Marks a binding (or binding set) as requiring an explicit name.
        """
        def __init__(self, value: str) -> None: ...
        def __repr__(self) -> str: ...
