"""
This type stub file was generated by pyright.
"""

from typing import Any

import attr

"""Config convenience class

This class encapsulates access functions to the environment configuration

"""

@attr.s(eq=False)
class Config:
    filename = ...
    def __attrs_post_init__(self) -> None: ...
    def resolve_path(self, path: str) -> str:
        """Resolve an absolute path

        Args:
            path (str): path to resolve

        Returns:
            str: the absolute path
        """
        ...

    def resolve_path_str_or_list(self, path: str | list[str]) -> list[str]:
        """
        Resolves a single path or multiple paths. Always returns a list (containing a single or
        multiple resolved paths).

        Args:
            path (str, list): path(s) to resolve

        Returns:
            list: absolute path(s)

        Raises:
            TypeError: if input is neither str nor list
        """
        ...

    def get_tool(self, tool: str) -> str:
        """Retrieve an entry from the tools subkey

        Args:
            tool (str): the tool to retrieve the path for

        Returns:
            str: path to the requested tools
        """
        ...

    def get_image_path(self, kind: str) -> str:
        """Retrieve an entry from the images subkey

        Args:
            kind (str): the kind of the image to retrieve the path for

        Returns:
            str: path to the image

        Raises:
            KeyError: if the requested image can not be found in the
                configuration
        """
        ...

    def get_path(self, kind: str) -> str:
        """Retrieve an entry from the paths subkey

        Args:
            kind (str): the type of path to retrieve the path for

        Returns:
            str: path to the path

        Raises:
            KeyError: if the requested image can not be found in the
                configuration
        """
        ...

    def get_option(self, name: str, default: Any = ...) -> Any:
        """Retrieve an entry from the options subkey

        Args:
            name (str): name of the option
            default (any): A default parameter in case the option can not be
                found

        Returns:
            any: value of the option or default parameter

        Raises:
            KeyError: if the requested image can not be found in the
                configuration
        """
        ...

    def set_option(self, name: str, value: Any) -> None:
        """Set an entry in the options subkey

        Args:
            name (str): name of the option
            value (any): the new value
        """
        ...

    def get_target_option(self, target: str, name: str, default: Any = ...) -> Any:
        """Retrieve an entry from the options subkey under the specified target
           subkey

        Args:
            target (str): name of the target
            name (str): name of the option
            default (any): A default parameter in case the option can not be
                found

        Returns:
            any: value of the option or default parameter

        Raises:
            KeyError: if the requested key can not be found in the
                configuration, or if the target can not be found in the
                configuration.
        """
        ...

    def set_target_option(self, target: str, name: str, value: Any) -> None:
        """Set an entry in the options subkey under the specified target subkey

        Args:
            target (str): name of the target
            name (str): name of the option
            value (any): the new value

        Raises:
            KeyError: if the requested target can not be found in the
                configuration
        """
        ...

    def get_targets(self) -> Any: ...
    def get_imports(self) -> list[Any]:
        """Helper function that returns the list of all imports

        Returns:
            List: List of files which should be imported
        """
        ...

    def get_paths(self) -> dict[Any, Any]:
        """Helper function that returns the subdict of all paths

        Returns:
            Dict: Dictionary containing all path definitions
        """
        ...

    def get_images(self) -> dict[Any, Any]:
        """Helper function that returns the subdict of all images

        Returns:
            Dict: Dictionary containing all image definitions
        """
        ...

    def get_features(self) -> set[Any]: ...
