"""
This type stub file was generated by pyright.
"""

class ConsoleLoggingReporter:
    """ConsoleLoggingReporter - Reporter that writes console log files

    Args:
        logpath (str): path to store the logfiles in
    """

    instance = ...
    @classmethod
    def start(cls, path):  # -> None:
        """starts the ConsoleLoggingReporter"""
        ...

    @classmethod
    def stop(cls):  # -> None:
        """stops the ConsoleLoggingReporter"""
        ...

    def __init__(self, logpath) -> None: ...
    def get_logfile(self, event):  # -> FileIO | None:
        """Returns the correct file handle from cache or creates a new file handle"""
        ...

    def notify(self, event):  # -> None:
        """This is the callback function for steps"""
        ...
