"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from typing import Any, Optional

import attr

from .config import Config
from .target import Target

@attr.s(eq=False)
class Environment:
    """An environment encapsulates targets."""

    targets: dict[str, Target] = attr.ib(init=False)
    config: Config = attr.ib(init=False)

    config_file: str = attr.ib(
        default="config.yaml", validator=attr.validators.instance_of(str)
    )
    interact: Callable[[object], str] = attr.ib(default=input, repr=False)

    def __attrs_post_init__(self) -> None: ...
    def get_target(self, role: str = ...) -> Optional[Target]:
        """Returns the specified target or None if not found.

        Each target is initialized as needed.
        """
        ...

    def get_features(self) -> set[Any]: ...
    def get_target_features(self) -> set[Any]: ...
    def cleanup(self) -> None: ...
