"""
This type stub file was generated by pyright.
"""

from typing import Any

import attr

@attr.s(eq=False)
class NoConfigFoundError(Exception):
    msg: str = ...

@attr.s(eq=False)
class NoSupplierFoundError(Exception):
    msg: str = ...
    filter: set[str] | None = ...

@attr.s(eq=False)
class InvalidConfigError(Exception):
    msg: str = ...

@attr.s(eq=False)
class NoDriverFoundError(NoSupplierFoundError): ...

@attr.s(eq=False)
class NoResourceFoundError(NoSupplierFoundError):
    found: list[Any] | None = ...

@attr.s(eq=False)
class NoStrategyFoundError(NoSupplierFoundError): ...

@attr.s(eq=False)
class RegistrationError(Exception):
    msg: str = ...
