"""
This type stub file was generated by pyright.
"""

from typing import TypeVar

_TCls = TypeVar("_TCls")

class TargetFactory:
    def __init__(self) -> None: ...
    def reg_resource(self, cls: _TCls) -> _TCls:
        """Register a resource with the factory.

        Returns the class to allow using it as a decorator."""
        ...

    def reg_driver(self, cls: _TCls) -> _TCls:
        """Register a driver with the factory.

        Returns the class to allow using it as a decorator."""
        ...

    @staticmethod
    def normalize_config(config):  # -> tuple[dict[Any, Any], dict[Any, Any]]:
        ...
    def make_resource(self, target, resource, name, args): ...
    def make_driver(self, target, driver, name, args): ...
    def make_target(self, name, config, *, env=...):  # -> Target:
        ...
    def class_from_string(self, string: str): ...

target_factory: TargetFactory = ...
