"""
This type stub file was generated by pyright.
"""

class StepReporter:
    _started = ...
    def __init__(self) -> None: ...
    @classmethod
    def start(cls):  # -> None:
        """starts the StepReporter"""
        ...

    @classmethod
    def stop(cls):  # -> None:
        """stops the StepReporter"""
        ...

    @staticmethod
    def notify(event):  # -> None:
        ...
