"""
This type stub file was generated by pyright.
"""

from typing import Any

import attr
from labgrid import Environment
from labgrid.strategy import Strategy

@attr.s(eq=False)
class Target:
    name: str = ...
    env: Environment | None = ...
    def __attrs_post_init__(self) -> None: ...
    def interact(self, msg: str) -> None: ...
    def update_resources(self) -> None:
        """
        Iterate over this target's resources, deactivate any active but
        unavailable resources and also deactivate any drivers using them.
        This ensures a consistent binding states for this target.
        """
        ...

    def await_resources(self, resources, timeout=..., avail=...):  # -> None:
        """
        Poll the given resources and wait until they are (un-)available.

        Args:
            resources (List): the resources to poll
            timeout (float): optional timeout
            avail (bool): optionally wait until the resources are unavailable with avail=False
        """
        ...

    def get_resource(self, cls, *, name=..., wait_avail=...):
        """
        Helper function to get a resource of the target.
        Returns the first valid resource found, otherwise a
        NoResourceFoundError is raised.

        Arguments:
        cls -- resource-class to return as a resource
        name -- optional name to use as a filter
        wait_avail -- wait for the resource to become available (default True)
        """
        ...

    def get_active_driver(self, cls, *, name=..., resource=...):
        """
        Helper function to get the active driver of the target.
        Returns the active driver found, otherwise None.

        Arguments:
        cls -- driver-class to return as a resource
        name -- optional name to use as a filter
        resource -- optional resource to use as a filter
        """
        ...

    def get_driver(self, cls, *, name=..., resource=..., activate=...):
        """
        Helper function to get a driver of the target.
        Returns the first valid driver found, otherwise None.

        Arguments:
        cls -- driver-class to return as a resource
        name -- optional name to use as a filter
        resource -- optional resource to use as a filter
        activate -- activate the driver (default True)
        """
        ...

    def get_strategy(self) -> Strategy:
        """
        Helper function to get the strategy of the target.

        Returns the Strategy, if exactly one exists and raises a
        NoStrategyFoundError otherwise.
        """
        ...

    def __getitem__(self, key):
        """
        Syntactic sugar to access drivers by class (optionally filtered by
        name).

        >>> from labgrid import Target
        >>> from labgrid.driver.fake import FakeConsoleDriver
        >>>
        >>> target = Target('main')
        >>> console = FakeConsoleDriver(target, 'console')
        >>> target.activate(console)
        >>> target[FakeConsoleDriver]
        FakeConsoleDriver(target=Target(name='main', env=None), name='console', state=<BindingState.active: 2>, txdelay=0.0)
        >>> target[FakeConsoleDriver, 'console']
        FakeConsoleDriver(target=Target(name='main', env=None), name='console', state=<BindingState.active: 2>, txdelay=0.0)
        """
        ...

    def set_binding_map(self, mapping) -> None:
        """
        Configure the binding name mapping for the next driver only.
        """
        ...

    def bind_resource(self, resource) -> None:
        """
        Bind the resource to this target.
        """
        ...

    def bind_driver(self, client) -> None:
        """
        Bind the driver to all suppliers (resources and other drivers).

        Currently, we only support binding all suppliers at once.
        """
        ...

    def bind(self, bindable) -> None: ...
    def activate(self, client: Any, name: str | None = ...) -> None:
        """
        Activate the client by activating all bound suppliers. This may require
        deactivating other clients.
        """
        ...

    def deactivate(self, client: Any, name: str | None = ...) -> list[Any]:
        """
        Recursively deactivate the client's clients and itself.

        This is needed to ensure that no client has an inactive supplier.

        Returns the list of all objects that were deactivated
        """
        ...

    def deactivate_all_drivers(self):  # -> None:
        """Deactivates all drivers in reversed order they were activated"""
        ...

    def export(self):  # -> dict[Any, Any]:
        """
        Export information from drivers.

        All drivers are deactivated before being exported, unless their
        skip_deactivate_on_export property is true.

        The Strategy can decide for which driver the export method is called and
        with which name. Otherwise, all drivers are exported.
        """
        ...

    def cleanup(self):  # -> None:
        """Clean up connected drivers and resources in reversed order"""
        ...
