"""
This type stub file was generated by pyright.
"""

import abc
from typing import Any

class CommandProtocol(abc.ABC):
    """Abstract class for the CommandProtocol"""
    @abc.abstractmethod
    def run(self, cmd: str) -> tuple[list[str], list[Any], int] | None:
        """
        Run a command
        """
        ...

    @abc.abstractmethod
    def run_check(self, cmd: str):
        """
        Run a command, return str if successful, ExecutionError otherwise
        """
        ...

    @abc.abstractmethod
    def get_status(self):
        """
        Get status of the Driver
        """
        ...

    @abc.abstractmethod
    def wait_for(
        self, cmd: str, pattern: str, timeout: float = 30, sleepduration: int = 1
    ) -> None:
        """
        Wait for a shell command to return with the specified output
        """
        ...

    @abc.abstractmethod
    def poll_until_success(
        self,
        cmd: str,
        *,
        expected: int = 0,
        tries: int | None = None,
        timeout: float = 30,
        sleepduration: int = 1,
    ) -> bool:
        """
        Repeatedly call a shell command until it succeeds
        """
        ...
