"""
This type stub file was generated by pyright.
"""

import abc
from re import Match
from typing import Any

from pexpect import EOF, TIMEOUT

class ConsoleProtocol(abc.ABC):
    """Abstract class for the ConsoleProtocol"""
    @abc.abstractmethod
    def read(self) -> bytes:
        """
        Read data from underlying port
        """
        ...

    @abc.abstractmethod
    def write(self, data: bytes) -> None:
        """
        Write data to underlying port
        """
        ...

    def sendline(self, line: str) -> None: ...
    def sendcontrol(self, char: str) -> None: ...
    def expect(
        self, pattern: str, timeout: float = ...
    ) -> tuple[
        int,
        Any | None,
        Any | Match[Any] | type[EOF] | type[TIMEOUT] | None,
        Any | type[EOF] | type[TIMEOUT] | None,
    ]: ...

    class Client(abc.ABC):
        @abc.abstractmethod
        def get_console_matches(self): ...
        @abc.abstractmethod
        def notify_console_match(self, pattern, match): ...
