"""
This type stub file was generated by pyright.
"""

import abc

class DigitalOutputProtocol(abc.ABC):
    """Abstract class providing the DigitalOutputProtocol interface"""
    @abc.abstractmethod
    def get(self) -> bool:
        """Implementations should return the status of the digital output."""
        ...

    @abc.abstractmethod
    def set(self, status: bool) -> None:
        """Implementations should set the status of the digital output"""
        ...
