"""
This type stub file was generated by pyright.
"""

import abc

class InfoProtocol(abc.ABC):
    """Abstract class providing the InfoProtocol interface"""
    @abc.abstractmethod
    def get_ip(self, interface: str = ...):
        """Implementations should return the IP address for the supplied
        interface."""
        ...

    @abc.abstractmethod
    def get_hostname(self):
        """Implementations should return the hostname for the supplied
        interface."""
        ...

    @abc.abstractmethod
    def get_service_status(self, service):
        """Implementations should return the status of a service"""
        ...
