"""
This type stub file was generated by pyright.
"""

import abc

class MMIOProtocol(abc.ABC):
    @abc.abstractmethod
    def read(self, address: int, size: int, count: int) -> bytes: ...
    @abc.abstractmethod
    def write(self, address: int, size: int, data: bytes) -> None: ...
