"""
This type stub file was generated by pyright.
"""

import abc

class PowerProtocol(abc.ABC):
    @abc.abstractmethod
    def on(self) -> None: ...
    @abc.abstractmethod
    def off(self) -> None: ...
    @abc.abstractmethod
    def cycle(self) -> None: ...
