"""
This type stub file was generated by pyright.
"""

import abc

class VideoProtocol(abc.ABC):
    @abc.abstractmethod
    def get_qualities(self): ...
    @abc.abstractmethod
    def stream(self, quality_hint=...): ...
