"""
This type stub file was generated by pyright.
"""

from typing import Any

import attr
from labgrid import Target

from ..driver import Driver

@attr.s(eq=False)
class StrategyError(Exception):
    msg: str = attr.ib(validator=attr.validators.instance_of(str))

@attr.s(eq=False)
class Strategy(Driver):
    """
    Represents a strategy which places a target into a requested state by
    calling specific drivers. A strategy usually needs to know some details of
    a given target.

    Life cycle:
    - create
    - bind (n times)
    - usage

    TODO: This might also be just a driver?
    """

    target: Target = ...

    def __attrs_post_init__(self) -> None: ...
    def on_client_bound(self, client) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    def resolve_conflicts(self, client) -> None: ...
    # def transition(self, status: Any, *, step: Step) -> None: ...
    def transition(self, status: Any) -> None: ...
    def force(self, status: Any) -> None: ...
    def prepare_export(self) -> dict[Any, Any]:
        """By default, export all drivers bound by the strategy."""
        ...
