"""
This type stub file was generated by pyright.
"""

import enum

import attr

from ..factory import target_factory
from ..step import step
from .common import Strategy

class Status(enum.Enum):
    """The possible states of a docker container"""

    unknown = ...
    gone = ...
    accessible = ...

@target_factory.reg_driver
@attr.s(eq=False)
class DockerStrategy(Strategy):
    """
    DockerStrategy enables the user to directly transition to a state
    where a fresh docker container has been created and is
    ready for access (e.g. shell access via SSH if the docker image
    runs an SSH daemon).
    """

    bindings = ...
    status = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @step(args=["status"])
    def transition(self, status):  # -> None:
        ...
