"""
This type stub file was generated by pyright.
"""

from ..step import step
from .common import Strategy, StrategyError

__all__ = [
    "InvalidGraphStrategyError",
    "GraphStrategyRuntimeError",
    "GraphStrategyError",
    "GraphStrategy",
]

class GraphStrategyError(StrategyError):
    """Generic GraphStrategy error"""

    ...

class InvalidGraphStrategyError(GraphStrategyError):
    """GraphStrategy error raised during initialization of broken strategies"""

    ...

class GraphStrategyRuntimeError(GraphStrategyError):
    """GraphStrategy error raised during runtime when used in unintended ways"""

    ...

class GraphStrategy(Strategy):
    def __attrs_post_init__(self):  # -> None:
        ...
    def invalidate(self):  # -> None:
        """
        Marks the path to the current state as out-of-date. Subsequent transition() calls will
        start from the root state.
        Will be called if exceptions in state methods occur.
        """
        ...

    @step(args=["state"])
    def transition(self, state, via=...):  # -> list[Any]:
        """
        Computes the path from root state (via "via" state, if given) to given state.
        If the computed path is fully incremental to the path executed previously, only the state's
        methods relative to the previous path are executed. Otherwise all states' methods of the
        computed path (starting from the root node) are executed.
        """
        ...

    def find_abs_path(self, state, via=...):  # -> list[Any]:
        """
        Computes the absolute path from the root state, via "via" (if given), to the given state.
        """
        ...

    def find_rel_path(self, path):
        """
        If the given path is fully incremental to the path executed before, returns the path
        relative to the previously executed one.
        Otherwise the given path is returned.
        """
        ...

    @property
    def graph(self):
        """
        Returns a graphviz.Digraph for the directed graph the inheriting strategy represents.

        The graph can be rendered with:
        ``mystrategy.graph.render("filename") # renders to filename.png``
        """
        ...

    @classmethod
    def depends(cls, *dependencies):  # -> Callable[..., Any]:
        """``@depends`` decorator used to list states the decorated state directly depends on."""
        ...
