"""
This type stub file was generated by pyright.
"""

import enum

import attr

from ..factory import target_factory
from ..step import step
from .common import Strategy

class Status(enum.Enum):
    unknown = ...
    off = ...
    shell = ...

@target_factory.reg_driver
@attr.s(eq=False)
class ShellStrategy(Strategy):
    """ShellStrategy - Strategy to switch to shell"""

    bindings = ...
    status = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @step(args=["status"])
    def transition(self, status, *, step):  # -> None:
        ...
    @step(args=["status"])
    def force(self, status, *, step):  # -> None:
        ...
