"""
This type stub file was generated by pyright.
"""

"""
This module contains helper functions for working with dictionaries.
"""

def diff_dict(old, new):  # -> Generator[tuple[Any, Any, Any], Any, None]:
    """
    Compares old and new dictionaries, yielding for each difference (key,
    old_value, new_value).
    None is used for missing values.
    """
    ...

def flat_dict(d):  # -> dict[str, Any]:
    ...
def filter_dict(d, cls, warn=...):  # -> dict[Any, Any]:
    """
    Returns a copy a dictionary which only contains the attributes defined on
    an attrs class.
    """
    ...

def find_dict(d, key):  # -> None:
    """
    Recursively search for a key in a dictionary

    Args:
        d (dict): The dictionary to recursively search through
        key (str): The key to search for
    """
    ...
