"""
This type stub file was generated by pyright.
"""

import pexpect
from labgrid.protocol.consoleprotocol import ConsoleProtocol

class PtxExpect(pexpect.spawn[bytes]):
    """labgrid Wrapper of the pexpect module.

    This class provides pexpect functionality for the ConsoleProtocol classes.
    driver: ConsoleProtocol object to be passed in
    """
    def __init__(self, driver: ConsoleProtocol) -> None:
        "Initializes a pexpect spawn instance with the required configuration"
        ...

    def send(self, s: str | bytes) -> int:
        "Write to underlying transport, return number of bytes written"
        ...

    def sendcontrol(self, char: str) -> int:
        """Send control character to underlying transport, e.g. Ctrl-C or Ctrl-Z."""
        ...

    def read_nonblocking(self, size: int = ..., timeout: float | None = ...) -> bytes:
        """Pexpects needs a nonblocking read function, simply use pyserial with
        a timeout of 0."""
        ...
