"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from subprocess import Popen

import attr

from ..step import step

re_vt100 = ...

def get_free_port() -> int:
    """Helper function to always return an unused port."""
    ...

def get_user() -> str:
    """Get the username of the current user."""
    ...

def set_nonblocking(fd: int) -> None: ...

_Callback = Callable[[bytes, Popen[str]], None]

@attr.s
class ProcessWrapper:
    callbacks = ...
    loglevel = ...
    @step(args=["command"], result=True, tag="process")
    def check_output(
        self,
        command: list[str],
        *,
        print_on_silent_log: bool = ...,
        input: str | None = ...,
        stdin: str | None = ...,
    ) -> bytes:
        """Run a command and supply the output to callback functions"""
        ...

    def register(self, callback: _Callback) -> None:
        """Register a callback with the ProcessWrapper"""
        ...

    def unregister(self, callback: _Callback) -> None:
        """Unregister a callback with the ProcessWrapper"""
        ...

    @staticmethod
    def log_callback(message: str, process: Popen[str]) -> None:
        """Logs process output message along with its pid."""
        ...

    @staticmethod
    def print_callback(message: str, _) -> None:
        """Prints process output message."""
        ...

    def enable_logging(self) -> None:
        """Enables process output to the logging interface."""
        ...

    def disable_logging(self) -> None:
        """Disables process output logging."""
        ...

    def enable_print(self) -> None:
        """Enables process output to print."""
        ...

    def disable_print(self) -> None:
        """Disables process output printing."""
        ...

processwrapper: ProcessWrapper = ...
