"""
This type stub file was generated by pyright.
"""

import attr

class ManagedFileError(Exception): ...

@attr.s
class ManagedFile:
    """The ManagedFile allows the synchronisation of a file to a remote host.
    It has to be created with the to be synced file and the target resource as
    argument:

    ::
        from labgrid.util.managedfile import ManagedFile

        ManagedFile("/tmp/examplefile", <your-resource>)

    Synchronisation is done with the sync_to_resource method.
    """

    local_path = ...
    resource = ...
    detect_nfs = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def sync_to_resource(self, symlink=...):  # -> None:
        """sync the file to the host specified in a resource

        Raises:
            ExecutionError: if the SSH connection/copy fails
        """
        ...

    def get_remote_path(self):  # -> str:
        """Retrieve the remote file path

        Returns:
            str: path to the file on the remote host
        """
        ...

    def get_hash(self):  # -> str:
        """Retrieve the hash of the file

        Returns:
            str: SHA256 hexdigest of the file
        """
        ...

    def get_user_cache_path(self):  # -> str:
        ...
