"""
This type stub file was generated by pyright.
"""

__all__ = ["proxymanager"]

class ProxyError(Exception): ...

class ProxyManager:
    """The ProxyManager class is only used inside labgrid.util.proxy (similar
    to a singleton), don't instanciate this class, use the exported
    proxymanager instead."""

    _force_proxy = ...
    @classmethod
    def force_proxy(cls, force_proxy):  # -> None:
        ...
    @classmethod
    def get_host_and_port(
        cls, res, *, default_port=..., force_port=...
    ):  # -> tuple[Literal['localhost'], Any | _RetAddress] | tuple[Any | Literal['localhost'], Any | _RetAddress | None]:
        """get host and port for a proxy connection from a Resource

        Args:
            res (Resource): The resource to retrieve the proxy for
            default_port (optional): TCP port to use if no other port is
                configured
            force_port (optional): TCP port to use instead of the one
                configured for the resource

        Returns:
            (host, port) host and port for the proxy connection

        Raises:
            ExecutionError: if the SSH connection/forwarding fails
        """
        ...

    @classmethod
    def get_url(cls, url, *, default_port=...):  # -> str:
        ...
    @classmethod
    def get_grpc_address(cls, address, *, default_port=...):  # -> str:
        ...
    @classmethod
    def get_command(cls, res, host, port, ifname=...):  # -> list[str] | None:
        """get argument list to start a proxy process connected to the target"""
        ...

proxymanager = ...
