"""
This type stub file was generated by pyright.
"""

from typing import Any

import attr

@attr.s(eq=False)
class QMPMonitor:
    monitor_out = ...
    monitor_in = ...
    def __attrs_post_init__(self) -> None: ...
    def execute(self, command: str, arguments: dict[str, str] = ...) -> Any: ...

@attr.s(eq=False)
class QMPError(Exception):
    msg = ...
