"""
This type stub file was generated by pyright.
"""

from typing import Any, TypeVar

import attr

__all__ = ["sshmanager", "SSHConnection", "ForwardError"]

def get_ssh_connect_timeout() -> int: ...
@attr.s
class SSHConnectionManager:
    """The SSHConnectionManager manages multiple SSH connections. This class
    should not be directly instantiated, use the exported sshmanager from this
    module instead.
    """

    _connections: dict[str, SSHConnection] = ...
    def __attrs_post_init__(self) -> None: ...
    def get(self, host: str) -> SSHConnection:
        """Retrieve or create a new connection to a given host

        Arguments:
            host (str): host to retrieve the connection for

        Returns:
            :obj:`SSHConnection`: the SSHConnection for the host"""
        ...

    def add_connection(self, connection: SSHConnection) -> None:
        """Add an existing SSHConnection to the manager.
        This is useful for manually created connections which should also be
        available via the manager.

        Arguments:
            connection (:obj:`SSHConnection`): SSHconnection to add to the manager
        """
        ...

    def remove_connection(self, connection: SSHConnection) -> None: ...
    def remove_by_name(self, name: str) -> None: ...
    def open(self, host: str) -> SSHConnection: ...
    def close(self, host: str) -> None: ...
    def request_forward(self, host: str, dest: str, port: int) -> int: ...
    def remove_forward(self, host: str, dest: str, port: int) -> None: ...
    def put_file(self, host: str, local_file: str, remote_file: str) -> None: ...
    def get_file(self, host: str, remote_file: str, local_file: str) -> None: ...
    def close_all(self) -> None:
        """Close all open connections and remove them from the manager"""
        ...

_TFunc = TypeVar("_TFunc")

def _check_connected(func: _TFunc) -> _TFunc: ...
@attr.s
class SSHConnection:
    """SSHConnections are individual connections to hosts managed by a control
    socket. In addition to command execution this class also provides an
    interface to manage port forwardings. These are used in the remote
    infrastructure to tunnel multiple connections over one SSH link.

    A public identity infrastructure is assumed, no extra username or passwords
    are supported."""

    host: str = ...
    _connected: bool = ...
    _tmpdir: str = ...
    _l_forwards = ...
    _r_forwards = ...
    def __init__(self, host: str) -> None: ...
    def __attrs_post_init__(self) -> None: ...
    @_check_connected
    def get_prefix(self) -> list[str]: ...
    @_check_connected
    def run(
        self,
        command: str,
        *,
        codec: str = "utf-8",
        decodeerrors: str = "strict",
        force_tty: bool = False,
        stderr_merge: bool = False,
        stderr_loglevel: int | None = None,
        stdout_loglevel: int | None = None,
    ) -> tuple[list[Any], list[Any], int | Any]:
        """Run a command over the SSHConnection

        Args:
            command (string): The command to run
            codec (string, optional): output encoding. Defaults to "utf-8".
            decodeerrors (string, optional): behavior on decode errors. Defaults
                 to "strict". Refer to stdtypes' bytes.decode for details.
            force_tty (bool, optional): force allocate a tty (ssh -tt). Defaults
                 to False
            stderr_merge (bool, optional): merge ssh subprocess stderr into
                 stdout. Defaults to False.
            stdout_loglevel (int, optional): log stdout with specific log level
                 as well. Defaults to None, i.e. don't log.
            stderr_loglevel (int, optional): log stderr with specific log level
                 as well. Defaults to None, i.e. don't log.

        returns:
            (stdout, stderr, returncode)
        """
        ...

    def run_check(
        self,
        command: str,
        *,
        codec: str = "utf-8",
        decodeerrors: str = "strict",
        force_tty: bool = False,
        stderr_merge: bool = False,
        stderr_loglevel: int | None = None,
        stdout_loglevel: int | None = None,
    ) -> list[Any]:
        """
        Runs a command over the SSHConnection
        returns the output if successful, raises ExecutionError otherwise.

        Except for the means of returning the value, this is equivalent to
        run.

        Args:
            command (string): The command to run
            codec (string, optional): output encoding. Defaults to "utf-8".
            decodeerrors (string, optional): behavior on decode errors. Defaults
                 to "strict". Refer to stdtypes' bytes.decode for details.
            force_tty (bool, optional): force allocate a tty (ssh -tt). Defaults
                 to False
            stderr_merge (bool, optional): merge ssh subprocess stderr into
                 stdout. Defaults to False.
            stdout_loglevel (int, optional): log stdout with specific log level
                 as well. Defaults to None, i.e. don't log.
            stderr_loglevel (int, optional): log stderr with specific log level
                 as well. Defaults to None, i.e. don't log.

        Returns:
            List[str]: stdout of the executed command if successful and
                       otherwise an ExecutionError Exception

        """
        ...

    @_check_connected
    def get_file(self, remote_file: str, local_file: str) -> None:
        """Get a file from the remote host"""
        ...

    @_check_connected
    def put_file(self, local_file: str, remote_path: str) -> None:
        """Put a file onto the remote host"""
        ...

    @_check_connected
    def add_port_forward(
        self, remote_host: str, remote_port: int, local_port: int | None = None
    ) -> int:
        """forward command"""
        ...

    @_check_connected
    def remove_port_forward(self, remote_host: str, remote_port: int) -> None:
        """cancel command"""
        ...

    @_check_connected
    def add_remote_port_forward(
        self, remote_port: int, local_port: int, remote_bind: str | None = None
    ) -> None:
        """remote forward command

        Note that the remote socket is not *bound* to any specific IP by
        default, making it reachable by the target. Also, 'GatewayPorts
        clientspecified' needs to be configured in the remote host's
        sshd_config.
        """
        ...

    @_check_connected
    def remove_remote_port_forward(
        self, remote_port: int, local_port: int, remote_bind: str | None = None
    ) -> None:
        """remote cancel command"""
        ...

    def connect(self) -> None: ...
    def isconnected(self) -> bool: ...
    @_check_connected
    def disconnect(self) -> None: ...
    def cleanup(self) -> None: ...

sshmanager: SSHConnectionManager = ...

@attr.s
class ForwardError(Exception):
    msg: str = ...
