"""
This type stub file was generated by pyright.
"""

import attr

@attr.s(eq=False)
class Timeout:
    """Reperents a timeout (as a deadline)"""

    timeout: float = ...
    def __attrs_post_init__(self) -> None: ...
    @property
    def remaining(self) -> float: ...
    @property
    def expired(self) -> bool: ...
