"""
This type stub file was generated by pyright.
"""

from collections.abc import Hashable, Mapping
from typing import Any, TypedDict, Unpack, overload

import yaml

"""
This module contains the custom YAML load and dump functions and associated
loader and dumper
"""

class Loader(yaml.SafeLoader): ...
class Dumper(yaml.SafeDumper): ...

def load(stream: yaml.reader._ReadStream) -> Any:  # pyright: ignore[reportPrivateUsage]
    """
    Wrapper for yaml load function with custom loader.
    """
    ...

class _DumpKwargs(TypedDict, total=False):
    Dumper: type[yaml.Dumper]

@overload
def dump(
    data: Any,
    stream: yaml.emitter._WriteStream[Any],  # pyright: ignore[reportPrivateUsage]
    **kwargs: Unpack[_DumpKwargs],
) -> None: ...
@overload
def dump(data: Any, stream: None = None, **kwargs: Unpack[_DumpKwargs]) -> bytes:
    """
    Wrapper for yaml dump function with custom dumper.
    """
    ...

def resolve_templates(
    data: list[Any] | dict[Hashable, Any], mapping: Mapping[str, object]
) -> None:
    """
    Iterate recursively over data and call substitute(mapping) on all
    Templates.
    """
    ...
