"""
This type stub file was generated by pyright.
"""

from typing import Dict, Type

import attr

from ..binding import BindingMixin

@attr.s(eq=False)
class Resource(BindingMixin):
    """
    Represents a resource which is used by drivers. It only stores information
    and does not implement any actual functionality.

    Resources can exist without a target, but they must be bound to one before
    use.

    Life cycle:

    - create
    - bind (n times)
    """

    avail = ...
    def __attrs_post_init__(self) -> None:
        ...
    @property
    def command_prefix(self) -> list[str]:
        ...
    def wrap_command(self, command: list[str]) -> list[str]:
        """
        Returns the command as-is, no need for command wrapping for local resources.

        Must stay compatible with NetworkResource.wrap_command().
        """
        ...

    @property
    def parent(self):  # -> None:
        ...
    @parent.setter
    def parent(self, value):  # -> None:
        ...
    def get_managed_parent(self):  # -> None:
        """
        For Resources which have been created at runtime, return the
        ManagedResource resource which created it.

        Returns None otherwise.
        """
        ...

    def poll(self):  # -> None:
        ...
    def get_bound_resources(self):  # -> set[Self]:
        """
        Resources only return themselves in a set, drivers will combine those sets.
        """
        ...

@attr.s(eq=False)
class NetworkResource(Resource):
    """
    Represents a remote Resource available on another computer.

    This stores a command_prefix to describe how to connect to the remote
    computer.

    Args:
        host (str): remote host the resource is available on
    """

    host = ...
    @property
    def command_prefix(self) -> list[str]:
        ...
    def wrap_command(self, command: list[str]) -> list[str]:
        """
        Returns shell-escaped command with prepended command_prefix.

        Must stay compatible with Resource.wrap_command().
        """
        ...

@attr.s(eq=False)
class ResourceManager:
    instances: Dict[Type[ResourceManager], ResourceManager] = ...
    @classmethod
    def get(cls) -> ResourceManager: ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_resource_added(self, resource: ManagedResource):  # -> None:
        ...
    def poll(self):  # -> None:
        ...

@attr.s(eq=False)
class ManagedResource(Resource):
    """
    Represents a resource which can appear and disappear at runtime. Every
    ManagedResource has a corresponding ResourceManager which handles these
    events.
    """

    manager_cls = ResourceManager
    timeout = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def poll(self):  # -> None:
        ...
    def get_managed_parent(self):  # -> Self:
        ...
