"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from .common import NetworkResource, Resource

@target_factory.reg_resource
@attr.s(eq=False)
class DediprogFlasher(Resource):
    vcc = ...

@target_factory.reg_resource
@attr.s(eq=False)
class NetworkDediprogFlasher(NetworkResource):
    vcc = ...
