"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from .common import ManagedResource, ResourceManager

"""
Auxiliary classes that assist DockerDriver. Specifically, DockerDaemon
and DockerManager will create the NetworkResource instance that is declared
in the specification (e.g. yaml) of DockerDriver.
"""

class DockerConstants:
    """Class constants for handling container cleanup"""

    DOCKER_LG_CLEANUP_LABEL = ...
    DOCKER_LG_CLEANUP_TYPE_AUTO = ...

@attr.s(eq=False)
class DockerManager(ResourceManager):
    """The DockerManager is responsible for cleaning up dangling
    containers and managing the managed NetworkService
    resources. Different docker daemons for different targets are
    allowed, but there has to be only one for each target.
    """
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_resource_added(self, resource):  # -> None:
        """If the resource added is a DockerDaemon, make sure this is the
        only one added for this target.  If it is, create a docker
        client to be used to communicate with the docker daemon.

        """
        ...

    def poll(self):  # -> None:
        """Ask associated DockerDaemon resource to check if associated
        NetworkService has come up."""
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class DockerDaemon(ManagedResource):
    """A resource identifying a docker daemon"""

    docker_daemon_url = ...
    manager_cls = DockerManager
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_client_bound(self, client):  # -> None:
        """Each time a docker driver binds to the DockerDaemon resource
        the docker driver network services list is iterated and for each
        network service defined a NetworkService resource instance is
        created with the parameters from the configuration file.

        """
        ...

    def on_poll(self, docker_client):  # -> None:
        """Check if associated NetworkService has come up."""
        ...
