"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from .common import ManagedResource, ResourceManager

@attr.s
class SNMPSwitch:
    """SNMPSwitch describes a switch accessible over SNMP. This class
    implements functions to query ports and the forwarding database."""

    hostname = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def update(self):  # -> None:
        """Update port status and forwarding database status

        Returns:
            None
        """
        ...

@attr.s
class EthernetPortManager(ResourceManager):
    """The EthernetPortManager periodically polls the switch for new updates."""
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_resource_added(self, resource):  # -> None:
        """Handler to execute when the resource is added

        Checks whether the resource can be managed by this Manager and starts
        the event loop.

        Args:
            resource(Resource): resource to check against

        Returns:
            None
        """
        ...

    def poll(self):  # -> None:
        """Updates the state with new information from the event loop

        Returns:
            None
        """
        ...

@target_factory.reg_resource
@attr.s
class SNMPEthernetPort(ManagedResource):
    """SNMPEthernetPort describes an ethernet port which can be queried over
    SNMP.

    Args:
        switch (str): hostname of the switch to query
        interface (str): name of the interface to query
    """

    manager_cls = EthernetPortManager
    switch = ...
    interface = ...
    def __attrs_post_init__(self):  # -> None:
        ...
