"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from .common import Resource

@target_factory.reg_resource
@attr.s(eq=False)
class HttpDigitalOutput(Resource):
    """This resource describes a generic HTTP-controlled output pin.

    Args:
        url (str): URL to use for setting a new state
        body_asserted (str): Request body to send to assert the output
        body_deasserted (str): Request body to send to de-assert the output
        method (str): HTTP method to use instead of PUT (the default) to set a new state

        url_get (str): URL to use for getting the state
        body_get_asserted (str): Regular Expression that matches an asserted response body
        body_get_deasserted (str): Regular Expression that matches a de-asserted response body
    """

    url = ...
    body_asserted = ...
    body_deasserted = ...
    method = ...
    url_get = ...
    body_get_asserted = ...
    body_get_deasserted = ...
