"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from .common import ManagedResource, ResourceManager

@attr.s(eq=False)
class LXAIOBusNodeManager(ResourceManager):
    def __attrs_post_init__(self):  # -> None:
        ...
    def poll(self):  # -> None:
        ...

@attr.s(eq=False)
class LXAIOBusNode(ManagedResource):
    """This resource describes a generic LXA IO BUs Node.

    Args:
        host (str): hostname of the owserver e.g. localhost:4304
        node (str): node name e.g. EthMux-5c12ca8b"""

    manager_cls = LXAIOBusNodeManager
    host = ...
    node = ...
    def __attrs_post_init__(self):  # -> None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class LXAIOBusPIO(LXAIOBusNode):
    """This resource describes a LXA IO Bus PIO Port.

    Args:
        pin (str): pin label e.g. OUT0
        invert (bool): optional, whether the logic level is inverted (active-low)"""

    pin = ...
    invert = ...
