"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from .base import SerialPort
from .common import Resource

@target_factory.reg_resource
@attr.s(eq=False)
class ModbusRTU(SerialPort, Resource):
    """This resource describes Modbus RTU instrument.

    Args:
        port (str): tty the instrument is connected to, e.g. '/dev/ttyUSB0'
        speed (int): optional, default is 115200
        address (int): slave address on the modbus, e.g. 16
        timeout (float): optional, timeout in seconds. Default is 0.25 s
    """

    address = ...
    timeout = ...
    def __attrs_post_init__(self):  # -> None:
        ...
