"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from .common import Resource

@attr.s(eq=False)
class BaseProvider(Resource):
    internal = ...
    external = ...
    def __attrs_post_init__(self):  # -> None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class TFTPProvider(BaseProvider): ...

@target_factory.reg_resource
@attr.s(eq=False)
class NFSProvider(Resource):
    def __attrs_post_init__(self):  # -> None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class HTTPProvider(BaseProvider): ...
