"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from .common import Resource

@target_factory.reg_resource
@attr.s(eq=False)
class PyVISADevice(Resource):
    """The PyVISADevice describes a test stimuli device controlled  with PyVISA

    Args:
        type (str): device resource type following the pyVISA resource syntax, e.g. ASRL, TCPIP...
        url (str): device identifier on selected resource, e.g. <ip> for TCPIP resource
        backend (str, default=''): Visa library backend, e.g. '@sim' for pyvisa-sim backend
    """

    type = ...
    url = ...
    backend = ...
