"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from .base import SerialPort
from .common import NetworkResource, Resource

@target_factory.reg_resource
@attr.s(eq=False)
class RawSerialPort(SerialPort, Resource):
    """RawSerialPort describes a serialport which is available on the local computer."""
    def __attrs_post_init__(self):  # -> None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class NetworkSerialPort(NetworkResource):
    """A NetworkSerialPort is a remotely accessible serialport, usually
    accessed via rfc2217 or tcp raw.

    Args:
        port (str): socket port to connect to
        speed (int): speed of the port e.g. 9800
        protocol (str): connection protocol: "raw" or "rfc2217"
    """

    port = ...
    speed = ...
    protocol = ...
