"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from .common import Resource

@target_factory.reg_resource
@attr.s(eq=False)
class SigrokDevice(Resource):
    """The SigrokDevice describes an attached sigrok device with driver,
    channel mapping and channel group

    Args:
        driver (str): driver to use with sigrok
        channels (str): a sigrok channel mapping as described in the sigrok-cli man page
        channel_group (str): a sigrok channel group as described in the sigrok-cli man page
    """

    driver = ...
    channels = ...
    channel_group = ...
