"""
This type stub file was generated by pyright.
"""

from typing import Any

import attr
from pyudev import Device

from ..factory import target_factory
from .base import NetworkInterface, SerialPort
from .common import ManagedResource, ResourceManager

@attr.s(eq=False)
class UdevManager(ResourceManager):
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_resource_added(self, resource):  # -> None:
        ...
    def poll(self):  # -> None:
        ...

@attr.s(eq=False)
class USBResource(ManagedResource):
    manager_cls = UdevManager
    match: dict[str, str] = ...
    device: Device | None = ...
    suggest: bool = ...
    def __attrs_post_init__(self) -> None: ...
    def filter_match(self, device: Device) -> bool: ...
    def suggest_match(self, device: Device) -> tuple[dict[Any, Any], list[Any]]: ...
    def try_match(self, device: Device) -> bool: ...
    def update(self) -> None: ...
    @property
    def busnum(self) -> int | None: ...
    @property
    def devnum(self) -> int | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def vendor_id(self) -> int | None: ...
    @property
    def model_id(self) -> int | None: ...
    def read_attr(self, attribute: str) -> bytes | None:
        """read uncached attribute value from sysfs

        pyudev currently supports only cached access to attributes, so we read
        directly from sysfs.
        """
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class USBSerialPort(USBResource, SerialPort):
    def __attrs_post_init__(self):  # -> None:
        ...
    def update(self):  # -> None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class USBMassStorage(USBResource):
    def __attrs_post_init__(self):  # -> None:
        ...
    @property
    def avail(self):  # -> bool:
        ...
    @avail.setter
    def avail(self, prop):  # -> None:
        ...
    @property
    def path(self):  # -> Any | None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class IMXUSBLoader(USBResource):
    def filter_match(self, device):  # -> bool:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class RKUSBLoader(USBResource):
    def filter_match(self, device):  # -> bool:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class MXSUSBLoader(USBResource):
    def filter_match(self, device):  # -> bool:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class AndroidUSBFastboot(USBResource):
    usb_vendor_id = ...
    usb_product_id = ...
    def filter_match(self, device):  # -> bool:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class AndroidFastboot(AndroidUSBFastboot):
    def __attrs_post_init__(self):  # -> None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class DFUDevice(USBResource):
    def filter_match(self, device):  # -> bool:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class USBNetworkInterface(USBResource, NetworkInterface):
    def __attrs_post_init__(self):  # -> None:
        ...
    def update(self):  # -> None:
        ...
    @property
    def if_state(self):  # -> str | None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class AlteraUSBBlaster(USBResource):
    def filter_match(self, device):  # -> bool:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class SigrokUSBDevice(USBResource):
    """The SigrokUSBDevice describes an attached sigrok device with driver and
    optional channel mapping, it is identified via usb using udev.

    This is used for devices which communicate over a custom USB protocol.

    Args:
        driver (str): driver to use with sigrok
        channels (str): a sigrok channel mapping as described in the sigrok-cli man page
        channel_group (str): a sigrok channel group as described in the sigrok-cli man page
    """

    driver = ...
    channels = ...
    channel_group = ...
    def __attrs_post_init__(self):  # -> None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class SigrokUSBSerialDevice(USBResource):
    """The SigrokUSBSerialDevice describes an attached sigrok device with driver and
    optional channel mapping, it is identified via usb using udev.

    This is used for devices which communicate over an emulated serial device.

    Args:
        driver (str): driver to use with sigrok
        channels (str): a sigrok channel mapping as described in the sigrok-cli man page
        channel_group (str): a sigrok channel group as described in the sigrok-cli man page
    """

    driver = ...
    channels = ...
    channel_group = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @property
    def path(self):  # -> Any | None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class USBSDWireDevice(USBResource):
    """The USBSDWireDevice describes an attached SDWire device,
    it is identified via USB using udev
    """

    control_path = ...
    disk_path = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @property
    def avail(self):  # -> bool:
        ...
    @avail.setter
    def avail(self, prop):  # -> None:
        ...
    def poll(self):  # -> None:
        ...
    def update(self):  # -> None:
        ...
    @property
    def path(self):  # -> Any | None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class USBSDMuxDevice(USBResource):
    """The USBSDMuxDevice describes an attached USBSDMux device,
    it is identified via USB using udev
    """

    control_path = ...
    disk_path = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @property
    def avail(self):  # -> bool:
        ...
    @avail.setter
    def avail(self, prop):  # -> None:
        ...
    def poll(self):  # -> None:
        ...
    def update(self):  # -> None:
        ...
    @property
    def path(self):  # -> Any | None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class USBHub(USBResource):
    """The USBHub describes a USB hub.

    This is mainly useful to monitor if all expected hubs are detected.
    """
    def __attrs_post_init__(self):  # -> None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class USBPowerPort(USBResource):
    """The USBPowerPort describes a single port on an USB hub which supports
    power control.

    Args:
        index (int): index of the downstream port on the USB hub
    """

    index = ...
    def __attrs_post_init__(self):  # -> None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class SiSPMPowerPort(USBResource):
    """This resource describes a SiS-PM (Silver Shield PM) power port.

    Args:
        index (int): port index
    """

    index = ...
    def filter_match(self, device):  # -> bool:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class USBVideo(USBResource):
    def filter_match(self, device):  # -> bool:
        ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @property
    def path(self):  # -> Any | None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class USBAudioInput(USBResource):
    index = ...
    def filter_match(self, device):  # -> bool:
        ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @property
    def path(self):  # -> Any | None:
        "the device node (for example /dev/snd/pcmC3D0c)"
        ...

    @property
    def alsa_name(self):  # -> str | None:
        "the ALSA device name (for example hw:CARD=3,DEV=0)"
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class USBTMC(USBResource):
    def __attrs_post_init__(self):  # -> None:
        ...
    @property
    def path(self):  # -> Any | None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class DeditecRelais8(USBResource):
    index = ...
    invert = ...
    def __attrs_post_init__(self):  # -> None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class HIDRelay(USBResource):
    index = ...
    invert = ...
    def filter_match(self, device):  # -> bool:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class USBFlashableDevice(USBResource):
    @property
    def devnode(self):  # -> Any | None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class LXAUSBMux(USBResource):
    """The LXAUSBMux describes an attached USBMux device,
    it is identified via USB using udev.
    """
    def __attrs_post_init__(self):  # -> None:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class USBDebugger(USBResource):
    def filter_match(self, device):  # -> bool:
        ...

@target_factory.reg_resource
@attr.s(eq=False)
class MatchedSysfsGPIO(USBResource):
    """The MatchedSysfsGPIO described a SysfsGPIO matched by Udev

    Args:
        pin (int): gpio pin number within the matched gpiochip."""

    pin = ...
    index = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def filter_match(self, device):  # -> bool:
        ...
    def update(self):  # -> None:
        ...
