"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from .common import Resource

@target_factory.reg_resource
@attr.s(eq=False)
class XenaManager(Resource):
    """Hostname/IP identifying the management address of the xena tester"""

    hostname = ...
