"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..protocol import CommandProtocol, LinuxBootProtocol
from ..step import step
from .commandmixin import CommandMixin
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class BareboxDriver(CommandMixin, Driver, CommandProtocol, LinuxBootProtocol):
    """BareboxDriver - Driver to control barebox via the console.
       BareboxDriver binds on top of a ConsoleProtocol.

       On activation, the BareboxDriver will look for the barebox prompt on the
       console, stopping any autoboot counters if necessary, and provide access
       to the barebox shell.

    Args:
        prompt (str): barebox prompt to match
        autoboot (regex): optional, autoboot message to match
        interrupt (str): optional, string to interrupt autoboot (use "\x03" for CTRL-C)
        bootstring (regex): optional, regex indicating that the Linux Kernel is booting
        password (str): optional, password to use for access to the shell
        login_timeout (int): optional, timeout for access to the shell
    """

    bindings = ...
    prompt = ...
    autoboot = ...
    interrupt = ...
    bootstring = ...
    password = ...
    login_timeout = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        """Activate the BareboxDriver

        This function tries to login if not already active
        """
        ...

    def on_deactivate(self):  # -> None:
        """Deactivate the BareboxDriver

        Simply sets the internal status to 0
        """
        ...

    @Driver.check_active
    @step(args=["cmd"])
    def run(
        self, cmd: str, *, timeout: int = ...
    ):  # -> tuple[list[str], list[Any], int] | None:
        ...
    @Driver.check_active
    @step()
    def reset(self):  # -> None:
        """Reset the board via a CPU reset"""
        ...

    def get_status(self):  # -> int:
        """Retrieve status of the BareboxDriver
        0 means inactive, 1 means active.

        Returns:
            int: status of the driver
        """
        ...

    @Driver.check_active
    def await_boot(self):  # -> None:
        """Wait for the initial Linux version string to verify we successfully
        jumped into the kernel.
        """
        ...

    @Driver.check_active
    def boot(self, name: str):  # -> None:
        """Boot the default or a specific boot entry

        Args:
            name (str): name of the entry to boot"""
        ...
