"""
This type stub file was generated by pyright.
"""

from ..step import step
from .common import Driver

class CommandMixin:
    """
    CommandMixin implementing common functions for drivers which support the CommandProtocol
    """
    def __attrs_post_init__(self) -> None: ...
    @Driver.check_active
    @step(args=["cmd", "pattern"])
    def wait_for(
        self, cmd: str, pattern: str, timeout: float = 30, sleepduration: int = 1
    ) -> None:
        """
        Wait until the pattern is detected in the output of cmd. Raises
        ExecutionError when the timeout expires.

        Args:
            cmd (str): command to run on the shell
            pattern (str): pattern as a string to look for in the output
            timeout (float): timeout for the pattern detection
            sleepduration (int): sleep time between the runs of the cmd
        """
        ...

    @Driver.check_active
    @step(args=["cmd", "expected", "tries", "timeout", "sleepduration"])
    def poll_until_success(
        self,
        cmd: str,
        *,
        expected: int = 0,
        tries: int | None = None,
        timeout: float = 30,
        sleepduration: int = 1,
    ) -> bool:
        """
        Poll a command until a specific exit code is detected.
        Takes a timeout and the number of tries to run the cmd.
        The sleepduration argument sets the duration between runs of the cmd.

        Args:
            cmd (str): command to run on the shell
            expected (int): exitcode to detect
            tries (int): number of tries, can be None for infinite tries
            timeout (float): timeout for the exitcode detection
            sleepduration (int): sleep time between the runs of the cmd

        Returns:
            bool: whether the command finally executed sucessfully
        """
        ...

    @Driver.check_active
    @step(args=["cmd"], result=True)
    def run_check(
        self,
        cmd: str,
        *,
        timeout: float = 30,
        codec: str = "utf-8",
        decodeerrors: str = "strict",
    ) -> list[str]:
        """
        External run_check function, only available if the driver is active.
        Runs the supplied command and returns the stdout, raises an
        ExecutionError otherwise.

        Args:
            cmd (str): command to run on the shell

        Returns:
            List[str]: stdout of the executed command
        """
        ...
