"""
This type stub file was generated by pyright.
"""

from typing import Any

import attr

from ..binding import BindingMixin

@attr.s(eq=False)
class Driver(BindingMixin):
    """
    Represents a driver which is used externally or by other drivers. It
    implements functionality based on directly accessing the Resource or by
    building on top of other Drivers.

    Life cycle:
    - create
    - bind (n times)
    - activate
    - usage
    - deactivate
    """
    def __attrs_post_init__(self) -> None: ...
    def get_priority(self, protocol: object) -> int:
        """Retrieve the priority for a given protocol

        Arguments:
        protocol - protocol to search for in the MRO

        Returns:
            Int: value of the priority if it is found, 0 otherwise.
        """
        ...

    def get_export_name(self) -> str:
        """Get the name to be used for exported variables.

        Falls back to the class name if the driver has no name.
        """
        ...

    def get_export_vars(self) -> dict[Any, Any]:
        """Get a dictionary of variables to be exported."""
        ...

    @property
    def skip_deactivate_on_export(self) -> bool:
        """Drivers are deactivated on export by default.

        If the driver can handle external accesses even while active, it can
        return True here.
        """
        ...

    def get_bound_resources(self) -> set[Any]:
        """Return the bound resources for a driver

        This recursively calls all suppliers and combines the sets of returned resources.
        """
        ...

def check_file(filename: str, *, command_prefix: list[str] = ...) -> None: ...
