"""
This type stub file was generated by pyright.
"""

from re import Match
from typing import Any, Literal

from pexpect import EOF, TIMEOUT

from ..step import step
from .common import Driver

class ConsoleExpectMixin:
    """
    Console driver mixin to implement the read, write, expect and sendline methods. It uses
    the internal _read and _write methods.

    The class using the ConsoleExpectMixin must provide a logger and a txdelay attribute.
    """
    def __attrs_post_init__(self) -> None:
        ...
    @Driver.check_active
    @step(result=True, tag="console")
    def read(self, size=..., timeout=..., max_size=...): ...
    @Driver.check_active
    @step(args=["data"], tag="console")
    def write(self, data: str) -> Literal[0]:
        ...
    @Driver.check_active
    def sendline(self, line: str) -> None:
        ...
    @Driver.check_active
    def sendcontrol(self, char: str) -> None:
        ...
    @Driver.check_active
    @step(args=["pattern"], result=True)
    def expect(
        self, pattern: str, timeout: float = -1
    ) -> tuple[
        int,
        Any | None,
        Any | Match[Any] | type[EOF] | type[TIMEOUT] | None,
        Any | type[EOF] | type[TIMEOUT] | None,
    ]: ...
    @Driver.check_active
    @step(args=["quiet_time"])
    def settle(self, quiet_time, timeout=...) -> bool: ...
    def resolve_conflicts(self, client) -> None:
        ...
