"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class DediprogFlashDriver(Driver):
    """The DediprogFlashDriver uses the dediprog utility to write an image
    to a raw rom. The driver is a pure wrapper of the dpcmd utility"""

    bindings = ...
    image = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
    def map_vcc(self):  # -> str:
        ...
    @Driver.check_active
    @step(title="call", args=["args"])
    def __call__(self, *args):  # -> None:
        ...
    @Driver.check_active
    @step(args=["filename"])
    def flash(self, filename=...):  # -> None:
        ...
    @Driver.check_active
    def erase(self):  # -> None:
        ...
