"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class DFUDriver(Driver):
    bindings = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
    @Driver.check_active
    @step(args=["altsetting", "filename"])
    def download(self, altsetting, filename):  # -> None:
        ...
    @step()
    def detach(self, altsetting):  # -> None:
        ...
    @step()
    def list(self):  # -> None:
        ...
