"""
This type stub file was generated by pyright.
"""

from enum import Enum

import attr
from labgrid.driver.common import Driver
from labgrid.factory import target_factory
from labgrid.protocol.powerprotocol import PowerProtocol

"""
Class for connecting to a docker daemon running on the host machine.
"""

class PullPolicy(Enum):
    """Pull policy for the `DockerDriver`.

    Modelled after `podman run --pull` / `docker run --pull`.

    * always: Always pull the image and throw an error if the pull fails.
    * missing: Pull the image only when the image is not in the local
      containers storage. Throw an error if no image is found and the pull
      fails.
    * never: Never pull the image but use the one from the local containers
      storage. Throw an error if no image is found.
    * newer: **Note** not supported by the driver, and therefore not
      implemented.
    """

    Always = ...
    Missing = ...
    Never = ...

def pull_policy_converter(value):  # -> PullPolicy:
    ...
@target_factory.reg_driver
@attr.s(eq=False)
class DockerDriver(PowerProtocol, Driver):
    """The DockerDriver is used to create docker containers.
    This is done via communication with a docker daemon.

    When a container is created the container is labeled with an
    cleanup strategy identifier. Currently only one strategy is
    implemented.  This strategy simply deletes all labgrid created
    containers before each test run. This is to ensure cleanup of
    dangling containers from crashed tests or hanging containers.

    Image pruning is not done by the driver.

    For detailed information about the arguments see the
    "Docker SDK for Python" documentation
    https://docker-py.readthedocs.io/en/stable/containers.html#container-objects

    Args:
        bindings (dict): The labgrid bindings
    Args passed to docker.create_container:
        image_uri (str): The uri of the image to fetch
        pull (str): Pull policy. Default policy is `always` for backward
        compatibility concerns
        command (str): The command to execute once container has been created
        volumes (list): The volumes to declare
        environment (list): Docker environment variables to set
        host_config (dict): Docker host configuration parameters
        network_services (list): Sequence of dicts each specifying a network \
                                 service that the docker container exposes.

    """

    bindings = ...
    image_uri = ...
    pull = ...
    command = ...
    volumes = ...
    container_name = ...
    environment = ...
    host_config = ...
    network_services = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        """On activation:
        1. Import docker module (_client and _container remain available)
        2. Connect to the docker daemon
        3. Pull requested image from docker registry if needed
        4. Create the new container according to parameters from conf
        """
        ...

    def on_deactivate(self):  # -> None:
        """Remove container after use"""
        ...

    def on(self):  # -> None:
        """Start the container created during activation"""
        ...

    def off(self):  # -> None:
        """Stop the container created during activation"""
        ...

    def cycle(self):  # -> None:
        """Cycle the docker container by stopping and starting it"""
        ...
