"""
This type stub file was generated by pyright.
"""

import attr

@attr.s(eq=False)
class ExecutionError(Exception):
    msg: str = ...
    stdout: list[str] = ...
    stderr: list[str] = ...

@attr.s(eq=False)
class CleanUpError(Exception):
    msg: str = ...
