"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..protocol import ConsoleProtocol
from .common import Driver
from .consoleexpectmixin import ConsoleExpectMixin

@target_factory.reg_driver
@attr.s(eq=False)
class ExternalConsoleDriver(ConsoleExpectMixin, Driver, ConsoleProtocol):
    """
    Driver implementing the ConsoleProtocol interface using a subprocess
    """

    cmd = ...
    txdelay = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def open(self):  # -> None:
        """Starts the subprocess, does nothing if it is already open"""
        ...

    def close(self):  # -> None:
        """Stops the subprocess, does nothing if it is already closed"""
        ...

    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
