"""
This type stub file was generated by pyright.
"""

from typing import Any

import attr

from ..factory import target_factory
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class AndroidFastbootDriver(Driver):
    # bindings = ...
    boot_image = ...
    flash_images = ...
    sparse_size = ...
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    @step(title="call", args=["args"])
    def __call__(self, *args: Any) -> None: ...
    @Driver.check_active
    @step(args=["filename"])
    def boot(self, filename: str | None = ...) -> None: ...
    @Driver.check_active
    @step(args=["partition", "filename"])
    def flash(self, partition: str, filename: str | None = ...) -> None: ...
    @Driver.check_active
    @step()
    def flash_all(self) -> None: ...
    @Driver.check_active
    @step(args=["partition"])
    def erase(self, partition: str) -> None: ...
    @Driver.check_active
    @step(args=["cmd"])
    def run(self, cmd: str) -> None: ...
    @Driver.check_active
    @step(title="continue")
    def continue_boot(self) -> None: ...
    @Driver.check_active
    @step(args=["var"])
    def getvar(self, var: str) -> str:
        """Return variable value via 'fastboot getvar <var>'."""
        ...

    @Driver.check_active
    @step(args=["var"])
    def oem_getenv(self, var: str) -> str:
        """Return barebox environment variable value via 'fastboot oem getenv <var>'."""
        ...
