"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..protocol import DigitalOutputProtocol
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class FileDigitalOutputDriver(Driver, DigitalOutputProtocol):
    """
    Two arbitrary string values false_repr and true_repr
    are defined as representations for False and True.
    These values are written to a file and read from it.
    If the file's content does not match any of the
    representations it defaults to False.
    A prime example for using this driver is Linux's sysfs.
    """

    filepath = ...
    false_repr = ...
    true_repr = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def get(self):  # -> bool:
        ...
    @Driver.check_active
    @step()
    def set(self, status):  # -> None:
        ...
