"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class FlashScriptDriver(Driver):
    bindings = ...
    script = ...
    args = ...
    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
    @Driver.check_active
    @step(args=["script"])
    def flash(self, script=..., args=...):  # -> None:
        """
        Transfers and remotely executes the script

        Args:
            script (str): optional, path to the script to write to bound Flashable Device
        """
        ...
