"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..protocol import BootstrapProtocol
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class FlashromDriver(Driver, BootstrapProtocol):
    """The Flashrom driver used the flashrom utility to write an image to a raw rom.
    The driver is a pure wrapper of the flashrom utility"""

    bindings = ...
    image = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
    @Driver.check_active
    @step(title="call", args=["args"])
    def __call__(self, *args):  # -> None:
        ...
    @Driver.check_active
    @step(args=["filename"])
    def load(self, filename=...):  # -> None:
        ...
