"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..protocol import VideoProtocol
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class HTTPVideoDriver(Driver, VideoProtocol):
    bindings = ...
    def get_qualities(self):  # -> tuple[Literal['high'], list[tuple[str, None]]]:
        ...
    @Driver.check_active
    def stream(self, quality_hint=...):  # -> int | None:
        ...
