"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class LXAUSBMuxDriver(Driver):
    """The LXAUSBMuxDriver uses the usbmuxctl tool to control the USBMux
    hardware
    """

    bindings = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @Driver.check_active
    @step(title="usbmux_set", args=["links"])
    def set_links(self, links):  # -> None:
        ...
