"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..protocol import PowerProtocol
from ..step import step
from .common import Driver

class MQTTError(Exception): ...

@target_factory.reg_driver
@attr.s(eq=False)
class TasmotaPowerDriver(Driver, PowerProtocol):
    bindings = ...
    delay = ...
    _client = ...
    _status = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def on(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def off(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def cycle(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def get(self):  # -> Any | bool:
        ...
