"""
This type stub file was generated by pyright.
"""

import contextlib

import attr

from ..factory import target_factory
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class NetworkInterfaceDriver(Driver):
    bindings = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
    @property
    def skip_deactivate_on_export(self):  # -> Literal[True]:
        ...
    def get_export_vars(self):  # -> dict[str, Any]:
        ...
    @Driver.check_active
    @step()
    def configure(self, settings):  # -> None:
        "Set a configuration on this interface and activate it."
        ...

    @Driver.check_active
    @step(args=["expected"])
    def wait_state(self, expected, timeout=...):  # -> None:
        """Wait until the expected state is reached or the timeout expires.

        Possible states include disconnected and activated. See NM's
        DeviceState for more details.
        """
        ...

    @Driver.check_active
    @step()
    def disable(self):  # -> None:
        "Disable and remove the created labgrid connection."
        ...

    @Driver.check_active
    @step()
    def get_active_settings(self):
        "Get the currently active settings from this interface."
        ...

    @Driver.check_active
    @step()
    def get_settings(self):
        "Get the settings of the labgrid connection for this interface."
        ...

    @Driver.check_active
    @step()
    def get_state(self):
        """Get the current state of this interface.

        This includes information such as the addresses or WiFi connection.
        """
        ...

    @Driver.check_active
    @step()
    def get_dhcpd_leases(self):
        """Get the list of active DHCP leases in shared mode.

        This requires read access to /var/lib/NetworkManager/dnsmasq-* on the
        exporter.
        """
        ...

    @Driver.check_active
    @step()
    def request_scan(self):
        "Request a scan to update the list visible access points."
        ...

    @Driver.check_active
    @step()
    def get_access_points(self, scan=...):
        """Get the list of currently visible access points.

        When scan is None (the default), it will automatically trigger a scan
        if the last scan is more than 30 seconds old.
        """
        ...

    @Driver.check_active
    @contextlib.contextmanager
    def forward_local(
        self, remote_host, remote_port, local_port=...
    ):  # -> Generator[Any | _RetAddress, Any, None]:
        """Forward a local port to an address and port via the exporter.

        A context manager that keeps the local port forwarded as long as the
        context remains valid. A connection can be made to the returned port on
        localhost and it will be forwarded to the address and port.

        If localport is not set, a random free port will be selected.

        usage:
            with netif.forward_local('127.0.0.1', 8080, local_port=1234) as local_port:
                # Use localhost:1234 here to connect to port 8080 on
                # the exporter

            with netif.forward_local('192.168.1.2', 8080) as local_port:
                # Use localhost:local_port here to connect to port 8080 on
                # 192.168.1.2

        returns:
            local_port
        """
        ...

    @Driver.check_active
    @contextlib.contextmanager
    def forward_remote(
        self, remote_port, local_port, remote_bind=...
    ):  # -> Generator[None, Any, None]:
        """Forward a remote port on the exporter to a local port.

        A context manager that keeps a remote port forwarded to a local port as
        long as the context remains valid. A connection can be made to the
        remote port on the target device will be forwarded to the returned local
        port on localhost.

        Note that the remote socket is not *bound* to any specific IP by
        default, making it reachable by the target. Also, 'GatewayPorts
        clientspecified' needs to be configured in the remote host's
        sshd_config.

        usage:
            with netif.forward_remote(8080, 8081) as local_port:
                # Connections to port 8080 on the exporter will be redirected to
                # localhost:8081
        """
        ...
