"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..protocol import DigitalOutputProtocol
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class OneWirePIODriver(Driver, DigitalOutputProtocol):
    bindings = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
    @Driver.check_active
    @step(args=["status"])
    def set(self, status):  # -> None:
        ...
    @Driver.check_active
    @step(result=["True"])
    def get(self):  # -> bool | Any:
        ...
