"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..protocol import PowerProtocol, ResetProtocol
from ..step import step
from .common import Driver

@attr.s(eq=False)
class PowerResetMixin(ResetProtocol):
    """
    ResetMixin implements the ResetProtocol for drivers which support the PowerProtocol
    """

    priorities = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def reset(self):  # -> None:
        ...

@target_factory.reg_driver
@attr.s(eq=False)
class ManualPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    """ManualPowerDriver - Driver to tell the user to control a target's power"""
    @Driver.check_active
    @step()
    def on(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def off(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def cycle(self):  # -> None:
        ...

@target_factory.reg_driver
@attr.s(eq=False)
class SiSPMPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    """SiSPMPowerDriver - Driver using a SiS-PM (Silver Shield PM) to control a
    target's power using the sispmctl tool - http://sispmctl.sourceforge.net/"""

    bindings = ...
    delay = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def on(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def off(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def cycle(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def get(self):  # -> bool:
        ...

@target_factory.reg_driver
@attr.s(eq=False)
class ExternalPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    """ExternalPowerDriver - Driver using an external command to control a target's power"""

    cmd_on = ...
    cmd_off = ...
    cmd_cycle = ...
    delay = ...
    @Driver.check_active
    @step()
    def on(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def off(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def cycle(self):  # -> None:
        ...

@target_factory.reg_driver
@attr.s(eq=False)
class NetworkPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    """NetworkPowerDriver - Driver using a networked power switch to control a target's power"""

    bindings = ...
    delay = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    def set_proxy_from_url(self):  # -> bool:
        """
        Some power backends (e.g. rest, simplerest) expect a URL in the host parameter. Try to
        handle the host parameter as a URL, extract the power backend port from it and set new
        proxied host parameter.
        """
        ...

    @Driver.check_active
    @step()
    def on(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def off(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def cycle(self):  # -> None:
        ...
    @Driver.check_active
    def get(self):  # -> Any:
        ...

@target_factory.reg_driver
@attr.s(eq=False)
class DigitalOutputPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    """
    DigitalOutputPowerDriver uses a DigitalOutput to control the power
    of a DUT.
    """

    bindings = ...
    delay = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def on(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def off(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def cycle(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def get(self): ...

@target_factory.reg_driver
@attr.s(eq=False)
class YKUSHPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    """YKUSHPowerDriver - Driver using a YEPKIT YKUSH switchable USB hub
    to control a target's power - https://www.yepkit.com/products/ykush.
    Uses ykushcmd tool to control the hub."""

    bindings = ...
    delay = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def on(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def off(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def cycle(self):  # -> None:
        ...
    @Driver.check_active
    def get(self):  # -> bool:
        ...

@target_factory.reg_driver
@attr.s(eq=False)
class USBPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    """USBPowerDriver - Driver using a power switchable USB hub and the uhubctl
    tool (https://github.com/mvp/uhubctl) to control a target's power"""

    bindings = ...
    delay = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def on(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def off(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def cycle(self):  # -> None:
        ...
    @Driver.check_active
    def get(self):  # -> bool:
        ...

@target_factory.reg_driver
@attr.s(eq=False)
class PDUDaemonDriver(Driver, PowerResetMixin, PowerProtocol):
    """PDUDaemonDriver - Driver using a PDU port available via pdudaemon"""

    bindings = ...
    delay = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def on(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def off(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def cycle(self):  # -> None:
        ...
    @Driver.check_active
    def get(self): ...
