"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..step import step
from .common import Driver

@attr.s(eq=False)
class BaseProviderDriver(Driver):
    @Driver.check_bound
    def get_export_vars(self):  # -> dict[str, Any]:
        ...
    @Driver.check_active
    @step(args=["filename"], result=True)
    def stage(self, filename): ...

@target_factory.reg_driver
@attr.s(eq=False)
class TFTPProviderDriver(BaseProviderDriver):
    bindings = ...

@attr.s
class NFSFile:
    host = ...
    export = ...
    relative_file_path = ...

@target_factory.reg_driver
@attr.s(eq=False)
class NFSProviderDriver(Driver):
    bindings = ...
    @Driver.check_bound
    def get_export_vars(self):  # -> dict[str, Any]:
        ...
    @Driver.check_active
    @step(args=["filename"], result=True)
    def stage(self, filename):  # -> NFSFile:
        ...

@target_factory.reg_driver
@attr.s(eq=False)
class HTTPProviderDriver(BaseProviderDriver):
    bindings = ...
