"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class PyVISADriver(Driver):
    """The PyVISADriver provides a transparent layer to the PyVISA module allowing to get a pyvisa resource

    Args:
        bindings (dict): driver to use with PyVISA
    """

    bindings = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
    @Driver.check_active
    def get_session(self):  # -> Any | None:
        ...
