"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..protocol import ConsoleProtocol, PowerProtocol
from ..step import step
from .common import Driver
from .consoleexpectmixin import ConsoleExpectMixin

"""The QEMUDriver implements a driver to use a QEMU target"""

@target_factory.reg_driver
@attr.s(eq=False)
class QEMUDriver(ConsoleExpectMixin, Driver, PowerProtocol, ConsoleProtocol):
    """
    The QEMUDriver implements an interface to start targets as qemu instances.

    The kernel, flash, rootfs and dtb arguments refer to images and paths
    declared in the environment configuration.

    Args:
        qemu_bin (str): reference to the tools key for the QEMU binary
        machine (str): QEMU machine type
        cpu (str): QEMU cpu type
        memory (str): QEMU memory size (ends with M or G)
        extra_args (str): optional, extra QEMU arguments passed directly to the QEMU binary
        boot_args (str): optional, additional kernel boot argument
        kernel (str): optional, reference to the images key for the kernel
        disk (str): optional, reference to the images key for the disk image
        disk_opts (str): optional, additional QEMU disk options
        flash (str): optional, reference to the images key for the flash image
        rootfs (str): optional, reference to the paths key for use as the virtio-9p filesystem
        dtb (str): optional, reference to the image key for the device tree
        bios (str): optional, reference to the image key for the bios image
        display (str, default="none"): optional, display output to enable; must be one of:
            none: Do not create a display device
            fb-headless: Create a headless framebuffer device
            egl-headless: Create a headless GPU-backed graphics card. Requires host support
            qemu-default: Don't override QEMU default settings
        nic (str): optional, configuration string to pass to QEMU to create a network interface
    """

    qemu_bin = ...
    machine = ...
    cpu = ...
    memory = ...
    extra_args = ...
    boot_args = ...
    kernel = ...
    disk = ...
    disk_opts = ...
    rootfs = ...
    dtb = ...
    flash = ...
    bios = ...
    display = ...
    nic = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def get_qemu_version(self, qemu_bin):  # -> tuple[int, int, int]:
        ...
    def get_qemu_base_args(self):  # -> list[Any]:
        """Returns the base command line used for Qemu without the options
        related to QMP. These options can be used to start an interactive
        Qemu manually for debugging tests
        """
        ...

    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
    @step()
    def on(self):  # -> None:
        """Start the QEMU subprocess, accept the unix socket connection and
        afterwards start the emulator using a QMP Command"""
        ...

    @step()
    def off(self):  # -> None:
        """Stop the emulator using a monitor command and await the exitcode"""
        ...

    def cycle(self):  # -> None:
        """Cycle the emulator by restarting it"""
        ...

    @step(result=True, args=["command", "arguments"])
    def monitor_command(self, command, arguments=...):  # -> Any:
        """Execute a monitor_command via the QMP"""
        ...

    def add_port_forward(
        self, proto, local_address, local_port, remote_address, remote_port
    ):  # -> None:
        ...
    def remove_port_forward(self, proto, local_address, local_port):  # -> None:
        ...
    def __str__(self) -> str: ...
