"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class QuartusHPSDriver(Driver):
    bindings = ...
    image = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @Driver.check_active
    @step(args=["filename", "address"])
    def flash(self, filename=..., address=...):  # -> None:
        ...
    @Driver.check_active
    @step(args=["address", "size"])
    def erase(self, address=..., size=...):  # -> None:
        ...
