"""
This type stub file was generated by pyright.
"""

import contextlib

import attr

from ..factory import target_factory
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class RawNetworkInterfaceDriver(Driver):
    bindings = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
    @Driver.check_active
    def set_interface_up(self):  # -> None:
        """Set bound interface up."""
        ...

    @Driver.check_active
    def set_interface_down(self):  # -> None:
        """Set bound interface down."""
        ...

    @Driver.check_active
    def get_state(self):  # -> str:
        """Returns the bound interface's operstate."""
        ...

    @Driver.check_active
    def wait_state(self, expected_state, timeout=...):  # -> None:
        """Wait until the expected state is reached or the timeout expires."""
        ...

    @Driver.check_active
    def get_ethtool_settings(self):  # -> Any:
        """
        Returns settings via ethtool of the bound network interface resource.
        """
        ...

    @Driver.check_active
    @step(args=["settings"])
    def ethtool_configure(self, **settings):  # -> None:
        """
        Change settings on interface.

        Supported settings are described in ethtool(8) --change (use "_" instead of "-").
        """
        ...

    @Driver.check_active
    def get_ethtool_eee_settings(self):  # -> Any:
        """
        Returns Energy-Efficient Ethernet settings via ethtool of the bound network interface
        resource.
        """
        ...

    @Driver.check_active
    @step(args=["settings"])
    def ethtool_configure_eee(self, **settings):  # -> None:
        """
        Change Energy-Efficient Ethernet settings via ethtool of the bound network interface
        resource.

        Supported settings are described in ethtool(8) --set-eee (use "_" instead of "-").
        """
        ...

    @Driver.check_active
    def get_ethtool_pause_settings(self):  # -> Any:
        """
        Returns pause parameters via ethtool of the bound network interface resource.
        """
        ...

    @Driver.check_active
    @step(args=["settings"])
    def ethtool_configure_pause(self, **settings):  # -> None:
        """
        Change pause parameters via ethtool of the bound network interface resource.

        Supported settings are described in ethtool(8) --pause
        """
        ...

    @Driver.check_active
    @step(args=["filename", "count", "timeout"])
    def start_record(self, filename, *, count=..., timeout=...):  # -> Popen[bytes]:
        """
        Starts tcpdump on bound network interface resource.

        Args:
            filename (str): name of a file to record to, or None to record to stdout
            count (int): optional, exit after receiving this many number of packets
            timeout (int): optional, number of seconds to capture packets before tcpdump exits
        Returns:
            Popen object of tcpdump process
        """
        ...

    @Driver.check_active
    @step(args=["timeout"])
    def stop_record(self, *, timeout=...):  # -> None:
        """
        Stops previously started tcpdump on bound network interface resource.

        Args:
            timeout (int): optional, maximum number of seconds to wait for the tcpdump process to
                           terminate
        """
        ...

    @contextlib.contextmanager
    def record(
        self, filename, *, count=..., timeout=...
    ):  # -> Generator[Popen[bytes], Any, None]:
        """
        Context manager to start/stop tcpdump on bound network interface resource.

        Either count or timeout must be specified.

        Args:
            filename (str): name of a file to record to, or None to live stream packets
            count (int): optional, exit after receiving this many number of packets
            timeout (int): optional, number of seconds to capture packets before tcpdump exits
        Returns:
            Popen object of tcpdump process. If filename is None, packets can be read from stdout
        """
        ...

    @Driver.check_active
    @step(args=["filename"])
    def start_replay(self, filename):  # -> Popen[bytes]:
        """
        Starts tcpreplay on bound network interface resource.

        Args:
            filename (str): name of a file to replay from
        Returns:
            Popen object of tcpreplay process
        """
        ...

    @Driver.check_active
    @step(args=["timeout"])
    def stop_replay(self, *, timeout=...):  # -> None:
        """
        Stops previously started tcpreplay on bound network interface resource.

        Args:
            timeout (int): optional, maximum number of seconds to wait for the tcpreplay process to
                           terminate
        """
        ...

    @contextlib.contextmanager
    def replay(
        self, filename, *, timeout=...
    ):  # -> Generator[Popen[bytes], Any, None]:
        """
        Context manager to start/stop tcpreplay on bound network interface resource.

        Args:
            filename (str): name of a file to replay from
            timeout (int): optional, maximum number of seconds to wait for the tcpreplay process to
                           terminate
        """
        ...

    @Driver.check_active
    @step()
    def get_statistics(self):  # -> Any:
        """
        Returns basic interface statistics of bound network interface resource.
        """
        ...

    @Driver.check_active
    def get_address(self):  # -> Any:
        """
        Returns the MAC address of the bound network interface resource.
        """
        ...
