"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..protocol import ResetProtocol
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class DigitalOutputResetDriver(Driver, ResetProtocol):
    """DigitalOutputResetDriver - Driver using a DigitalOutput to reset the
    target"""

    bindings = ...
    delay = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def reset(self):  # -> None:
        ...
