"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..protocol import DigitalOutputProtocol
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class SerialPortDigitalOutputDriver(Driver, DigitalOutputProtocol):
    """
    Controls the state of a GPIO using the control lines of a serial port.

    This driver uses the flow-control pins of a serial port (for example
    an USB-UART-dongle) to control some external power switch. You may connect
    some kind of relay board to the flow control pins.

    The serial port should NOT be used for serial communication at the same
    time. This will probably reset the flow-control signals.

    Usable signals are DTR and RTS.
    """

    bindings = ...
    signal = ...
    invert = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def get(self):  # -> bool:
        ...
    @Driver.check_active
    @step()
    def set(self, value):  # -> None:
        ...
