"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..protocol import ConsoleProtocol
from .common import Driver
from .consoleexpectmixin import ConsoleExpectMixin

@target_factory.reg_driver
@attr.s(eq=False)
class SerialDriver(ConsoleExpectMixin, Driver, ConsoleProtocol):
    """
    Driver implementing the ConsoleProtocol interface over a SerialPort connection
    """

    bindings = ...
    txdelay = ...
    timeout = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
    @Driver.check_bound
    def get_export_vars(self):  # -> dict[str, str]:
        ...
    def open(self):  # -> None:
        """Opens the serialport, does nothing if it is already open"""
        ...

    def close(self):  # -> None:
        """Closes the serialport, does nothing if it is already closed"""
        ...

    def __str__(self) -> str: ...
