"""
This type stub file was generated by pyright.
"""

from typing import Any

import attr

from ..factory import target_factory
from ..protocol import CommandProtocol, ConsoleProtocol, FileTransferProtocol
from ..step import step
from .commandmixin import CommandMixin
from .common import Driver

"""The ShellDriver provides the CommandProtocol, ConsoleProtocol and
 InfoProtocol on top of a SerialPort."""

@target_factory.reg_driver
@attr.s(eq=False)
class ShellDriver(CommandMixin, Driver, CommandProtocol, FileTransferProtocol):
    """ShellDriver - Driver to execute commands on the shell
    ShellDriver binds on top of a ConsoleProtocol.

    On activation, the ShellDriver will look for the login prompt on the console,
    and login to provide shell access.

    Args:
        prompt (regex): the shell prompt to detect
        login_prompt (regex): the login prompt to detect
        username (str): username to login with
        password (str): password to login with
        keyfile (str): keyfile to bind mount over users authorized keys
        login_timeout (int): optional, timeout for login prompt detection
        console_ready (regex): optional, pattern used by the kernel to inform the user that a
            console can be activated by pressing enter.
        await_login_timeout (int): optional, time in seconds of silence that needs to pass before
            sending a newline to device.
        post_login_settle_time (int): optional, seconds of silence after logging in
            before check for a prompt. Useful when the console is interleaved with boot
            output which may interrupt prompt detection.
    """

    console: ConsoleProtocol  # type: ignore
    # bindings = ...
    prompt: str = ...
    login_prompt: str = ...
    username: str = ...
    password: str = ...
    keyfile: str = ...
    login_timeout: int = ...
    console_ready: str = ...
    await_login_timeout: int = ...
    post_login_settle_time: int = ...
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    @step(args=["cmd"], result=True)
    def run(
        self, cmd: str, timeout: float = ..., codec=..., decodeerrors=...
    ) -> tuple[list[str], list[Any], int]: ...
    @step()
    def get_status(self):  # -> int:
        """Returns the status of the shell-driver.
        0 means not connected/found, 1 means shell
        """
        ...

    @Driver.check_active
    def put_ssh_key(self, keyfile_path):  # -> None:
        ...
    @Driver.check_active
    def put_bytes(self, buf: bytes, remotefile: str):  # -> None:
        """Upload a file to the target.
        Will silently overwrite the remote file if it already exists.

        Args:
            buf (bytes): file contents
            remotefile (str): destination filename on the target

        Raises:
            ExecutionError: if something went wrong
        """
        ...

    @Driver.check_active
    def put(self, localfile: str, remotefile: str):  # -> None:
        """Upload a file to the target.
        Will silently overwrite the remote file if it already exists.

        Args:
            localfile (str): source filename on the local machine
            remotefile (str): destination filename on the target

        Raises:
            IOError: if the provided localfile could not be found
            ExecutionError: if something else went wrong
        """
        ...

    @Driver.check_active
    def get_bytes(self, remotefile: str):  # -> bytes:
        """Download a file from the target.

        Args:
            remotefile (str): source filename on the target

        Returns:
            (bytes) file contents

        Raises:
            ExecutionError: if something went wrong
        """
        ...

    @Driver.check_active
    def get(self, remotefile: str, localfile: str):  # -> None:
        """Download a file from the target.
        Will silently overwrite the local file if it already exists.

        Args:
            remotefile (str): source filename on the target
            localfile (str): destination filename on the local machine (can be relative)

        Raises:
            IOError: if localfile could not be written
            ExecutionError: if something went wrong
        """
        ...

    @Driver.check_active
    def run_script(
        self, data: bytes, timeout: int = ...
    ):  # -> tuple[list[str], list[Any], int]:
        """Upload a script to the target and run it.

        Args:
            data (bytes): script data
            timeout (int): timeout for the script to finish execution

        Returns:
            Tuple of (stdout: str, stderr: str, return_value: int)

        Raises:
            ExecutionError: if something went wrong
        """
        ...

    @Driver.check_active
    def run_script_file(
        self, scriptfile: str, *args, timeout: int = ...
    ):  # -> tuple[list[str], list[Any], int]:
        """Upload a script file to the target and run it.

        Args:
            scriptfile (str): source file on the local file system to upload to the target
            *args: (list of str): any arguments for the script as positional arguments
            timeout (int): timeout for the script to finish execution

        Returns:
            Tuple of (stdout: str, stderr: str, return_value: int)

        Raises:
            ExecutionError: if something went wrong
            IOError: if the provided localfile could not be found
        """
        ...

    @Driver.check_active
    def get_default_interface_device_name(self, version=...):  # -> Any:
        """Retrieve the default route's interface device name.

        Args:
            version (int): IP version

        Returns:
            Name of the device of the default route

        Raises:
            ExecutionError: if no or multiple routes are set up
        """
        ...

    @Driver.check_active
    def get_ip_addresses(self, device=...):  # -> list[IPv4Interface | IPv6Interface]:
        """Retrieves IP addresses for given interface name.

        Note that although the return type is named IPv4Interface/IPv6Interface, it contains an IP
        address with the corresponding network prefix.

        Args:
            device (str): Name of the interface to query, defaults to default route's device name.

        Returns:
            List of IPv4Interface or IPv6Interface objects
        """
        ...
