"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..protocol import PowerProtocol
from ..step import step
from .common import Driver
from .powerdriver import PowerResetMixin

@attr.s(eq=False)
class SigrokCommon(Driver):
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...

@target_factory.reg_driver
@attr.s(eq=False)
class SigrokDriver(SigrokCommon):
    """The SigrokDriver uses sigrok-cli to record samples and expose them as python dictionaries.

    Args:
        bindings (dict): driver to use with sigrok
    """

    bindings = ...
    @Driver.check_active
    def capture(self, filename, samplerate=...):  # -> None:
        ...
    @Driver.check_active
    def stop(self):  # -> list[dict[str | Any, str | Any]]:
        ...
    @Driver.check_active
    def analyze(self, args, filename=...):  # -> list[dict[str, str | Any]]:
        ...

@target_factory.reg_driver
@attr.s(eq=False)
class SigrokPowerDriver(SigrokCommon, PowerResetMixin, PowerProtocol):
    """The SigrokPowerDriverDriver uses sigrok-cli to control a PSU and collect
    measurements.

    Args:
        bindings (dict): driver to use with sigrok
    """

    bindings = ...
    delay = ...
    max_voltage = ...
    max_current = ...
    @Driver.check_active
    @step()
    def on(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def off(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def cycle(self):  # -> None:
        ...
    @Driver.check_active
    @step(args=["value"])
    def set_voltage_target(self, value):  # -> None:
        ...
    @Driver.check_active
    @step(args=["value"])
    def set_current_limit(self, value):  # -> None:
        ...
    @Driver.check_active
    @step(result=True)
    def get(self):  # -> bool:
        ...
    @Driver.check_active
    @step(result=True)
    def measure(self):  # -> dict[Any, Any]:
        ...

@target_factory.reg_driver
@attr.s(eq=False)
class SigrokDmmDriver(SigrokCommon):
    """
    This driver wraps around a single channel DMM controlled by sigrok.
    It has been tested with Unit-T UT61C and UT61B devices but probably also
    works with other single chnnel DMMs.

    This driver binds to a SigrokUsbDevice.
    Make sure to select the correct driver for your DMM there.

    Example usage:
    > resources:
    >   - SigrokUSBDevice:
    >       driver: uni-t-ut61c
    >       match:
    >         'ID_PATH': pci-0000:07:00.4-usb-0:2:1.0
    > drivers:
    >   - SigrokDmmDriver: {}

    Args:
        bindings (dict): driver to use with sigrok
    """

    bindings = ...
    @Driver.check_active
    @step(result=True)
    def capture(self, samples, timeout=...):  # -> None:
        """
        Starts to read samples from the DMM.
        This method returns once sampling has been started. Sampling continues in the background.

        Note: We use subprocess.PIPE to buffer the samples.
        When this buffer is too small for the number of samples requested sampling may stall.

        Args:
            samples: Number of samples to obtain
            timeout: Timeout after which sampling should be stopped.
                     If None: timeout[s] = samples * 1s + 5s
                     If int: Timeout in [s]

        Raises:
            RuntimeError() if a capture is already running.
        """
        ...

    @Driver.check_active
    @step(result=True)
    def stop(self):  # -> tuple[str, list[Any]]:
        """
        Waits for sigrok to complete and returns all samples obtained afterwards.
        This function blocks until either sigrok has terminated or the timeout has been reached.

        Returns:
            (unit_spec, [sample, ...])

        Raises:
            RuntimeError() if capture has not been started
        """
        ...

    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
