"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..step import step
from .common import Driver
from .ubootdriver import UBootDriver

@target_factory.reg_driver
@attr.s(eq=False)
class SmallUBootDriver(UBootDriver):
    """
    SmallUBootDriver is meant as a driver for UBoot with only little
    functionality compared to standard a standard UBoot.
    Especially is copes with the following limitations:

    - The UBoot does not have a real password-prompt but can be activated by
      entering a "secret" after a message was displayed.
    - The command line is does not have a build-in echo command. Thus this
      driver uses 'Unknown Command' messages as marker before and after the
      output of a command.
    - Since there is no echo we can not return the exit code of the command.
      Commands will always return 0 unless the command was not found.

    This driver needs the following features activated in UBoot to work:

    - The UBoot must not have real password prompt. Instead it must be
      keyword activated.
      For example it should be activated by a dialog like the following:
      UBoot: "Autobooting in 1s..."
      Labgrid: "secret"
      UBoot: <switching to console>
    - The UBoot must be able to parse multiple commands in a single
      line separated by ";".
    - The UBoot must support the "bootm" command to boot from a
      memory location.

    This driver was created especially for the following devices:

    - TP-Link WR841 v11

    Args:
        boot_secret (str): optional, secret used to unlock prompt
        boot_secret_nolf (bool): optional, send boot_secret without new line
        login_timeout (int): optional, timeout for login prompt detection,
    """

    boot_expression = ...
    boot_secret = ...
    boot_secret_nolf = ...
    login_timeout = ...
    @Driver.check_active
    @step(args=["name"], result=True)
    def boot(self, name):  # -> None:
        """
        Boot the device from the given memory location using 'bootm'.

        Args:
            name (str): address to boot
        """
        ...
