"""
This type stub file was generated by pyright.
"""

import contextlib

import attr

from ..factory import target_factory
from ..protocol import CommandProtocol, FileTransferProtocol
from ..step import step
from .commandmixin import CommandMixin
from .common import Driver

"""The SSHDriver uses SSH as a transport to implement CommandProtocol and FileTransferProtocol"""

@target_factory.reg_driver
@attr.s(eq=False)
class SSHDriver(CommandMixin, Driver, CommandProtocol, FileTransferProtocol):
    """SSHDriver - Driver to execute commands via SSH"""

    bindings = ...
    priorities = ...
    keyfile = ...
    stderr_merge = ...
    connection_timeout = ...
    explicit_sftp_mode = ...
    explicit_scp_mode = ...
    username = ...
    password = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
    @property
    def skip_deactivate_on_export(self):  # -> Literal[True]:
        ...
    @Driver.check_active
    @step(args=["cmd"], result=True)
    def run(
        self, cmd, codec=..., decodeerrors=..., timeout=...
    ):  # -> tuple[list[str], list[str], int | Any]:
        ...
    def interact(self, cmd=...):  # -> int:
        ...
    @Driver.check_active
    @contextlib.contextmanager
    def forward_local_port(
        self, remoteport, localport=...
    ):  # -> Generator[_RetAddress | Any, Any, None]:
        """Forward a local port to a remote port on the target

        A context manager that keeps a local port forwarded to a remote port as
        long as the context remains valid. A connection can be made to the
        returned port on localhost and it will be forwarded to the remote port
        on the target device

        usage:
            with ssh.forward_local_port(8080) as localport:
                # Use localhost:localport here to connect to port 8080 on the
                # target

        returns:
        localport
        """
        ...

    @Driver.check_active
    @contextlib.contextmanager
    def forward_remote_port(
        self, remoteport, localport
    ):  # -> Generator[None, Any, None]:
        """Forward a remote port on the target to a local port

        A context manager that keeps a remote port forwarded to a local port as
        long as the context remains valid. A connection can be made to the
        remote on the target device will be forwarded to the returned local
        port on localhost

        usage:
            with ssh.forward_remote_port(8080, 8081) as localport:
                # Connections to port 8080 on the target will be redirected to
                # localhost:8081
        """
        ...

    @Driver.check_active
    @contextlib.contextmanager
    def forward_unix_socket(
        self, unixsocket, localport=...
    ):  # -> Generator[_RetAddress | Any, Any, None]:
        """Forward a unix socket on the target to a local port

        A context manager that keeps a unix socket forwarded to a local port as
        long as the context remains valid. A connection can be made to the
        remote socket on the target device will be forwarded to the returned
        local port on localhost

        usage:
            with ssh.forward_unix_socket("/run/docker.sock") as localport:
                # Use localhost:localport here to connect to the socket on the
                # target

        returns:
        localport
        """
        ...

    @Driver.check_active
    @step(args=["src", "dst"])
    def scp(self, *, src, dst):  # -> int:
        ...
    @Driver.check_active
    @step(args=["src", "dst", "extra"])
    def rsync(self, *, src, dst, extra=...):  # -> int:
        ...
    @Driver.check_active
    @step(args=["path", "mountpoint"])
    def sshfs(self, *, path, mountpoint):  # -> None:
        ...
    def get_status(self):  # -> Literal[1]:
        """The SSHDriver is always connected, return 1"""
        ...

    @Driver.check_active
    @step(args=["filename", "remotepath"])
    def put(self, filename, remotepath=...):  # -> None:
        ...
    @Driver.check_active
    @step(args=["filename", "destination"])
    def get(self, filename, destination=...):  # -> None:
        ...
