"""
This type stub file was generated by pyright.
"""

from typing import Any

import attr

from ..factory import target_factory
from ..protocol import CommandProtocol, LinuxBootProtocol
from ..step import step
from .commandmixin import CommandMixin
from .common import Driver

"""The U-Boot Module contains the UBootDriver"""

@target_factory.reg_driver
@attr.s(eq=False)
class UBootDriver(CommandMixin, Driver, CommandProtocol, LinuxBootProtocol):
    """UBootDriver - Driver to control uboot via the console.
    UBootDriver binds on top of a ConsoleProtocol.

    Args:
        prompt (str): optional, U-Boot prompt
        password (str): optional, password to unlock U-Boot
        init_commands (tuple): optional, tuple of commands to run after unlock
        autoboot (str): optional, string to search for to interrupt autoboot
        interrupt (str): optional, character to interrupt autoboot and go to prompt
        password_prompt (str): optional, string to detect the password prompt
        boot_expression (str): optional, deprecated
        bootstring (str): optional, string that indicates that the Kernel is booting
        boot_command (str): optional boot command to boot target
        login_timeout (int): optional, timeout for login prompt detection
        boot_timeout (int): optional, timeout for initial Linux Kernel version detection

    """

    # bindings = ...
    prompt: str = ...
    autoboot: str = ...
    password: str = ...
    interrupt: str = ...
    init_commands: tuple[str] = ...
    password_prompt: str = ...
    boot_expression: str = ...
    bootstring: str = ...
    boot_command: str = ...
    boot_commands: dict[str, str] = ...
    login_timeout: int = ...
    boot_timeout: int = ...
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None:
        """Activate the UBootDriver

        This function checks for a prompt and awaits it if not already active
        """
        ...

    def on_deactivate(self) -> None:
        """Deactivate the UBootDriver

        Simply sets the internal status to 0
        """
        ...

    @Driver.check_active
    @step(args=["cmd"], result=True)
    def run(
        self, cmd: str, timeout: int = ...
    ) -> tuple[list[str], list[Any], int] | None:
        """
        Runs the specified command on the shell and returns the output.

        Args:
            cmd (str): command to run on the shell
            timeout (int): optional, how long to wait for completion

        Returns:
            Tuple[List[str],List[str], int]: if successful, None otherwise
        """
        ...

    def get_status(self) -> int:
        """Retrieve status of the UBootDriver.
        0 means inactive, 1 means active.

        Returns:
            int: status of the driver
        """
        ...

    @Driver.check_active
    @step()
    def reset(self) -> None:
        """Reset the board via a CPU reset"""
        ...

    @Driver.check_active
    @step()
    def await_boot(self) -> None:
        """Wait for the initial Linux version string to verify we successfully
        jumped into the kernel.
        """
        ...

    @Driver.check_active
    @step(args=["name"])
    def boot(self, name: str = "") -> None:
        """Boot the default or a specific boot entry

        Args:
            name (str): name of the entry to boot"""
        ...
