"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class USBAudioInputDriver(Driver):
    """
    This driver provides access to a USB audio input device using ALSA and gstreamer.

    When using this driver in a Python venv, you may need to allow access to
    the gi (GObject Introspection) module from the system. This can be done by
    crating a symlink:
    ln -s /usr/lib/python3/dist-packages/gi $VENV/lib/python*/site-packages/
    """

    bindings = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @Driver.check_active
    @step()
    def start_sender(self):  # -> Popen[bytes]:
        """Return a subprocess which provides audio data in a matroska container on stdout"""
        ...

    @Driver.check_active
    @step()
    def create_gst_src(self):  # -> USBAudioInputBin:
        """Returns a newly create gstreamer bin with a single audio output pad."""
        ...

    @Driver.check_active
    @step(result=True)
    def measure_level(self):  # -> dict[Any, Any]:
        """Returns the current peak and rms value (measured with the gst level element)"""
        ...

    @Driver.check_active
    @step()
    def play(self):  # -> int | Any:
        """Plays the captured audio via gstreamer's autoaudiosink"""
        ...
