"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..step import step
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class USBSDMuxDriver(Driver):
    """The USBSDMuxDriver uses the usbsdmux tool
    (https://github.com/pengutronix/usbsdmux) to control the USB-SD-Mux
    hardware

    Args:
        bindings (dict): driver to use with usbsdmux
    """

    bindings = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    @Driver.check_active
    @step(title="sdmux_set", args=["mode"])
    def set_mode(self, mode):  # -> None:
        ...
    @Driver.check_active
    @step(title="sdmux_get")
    def get_mode(self):  # -> str:
        ...
