"""
This type stub file was generated by pyright.
"""

import enum

import attr

from ..factory import target_factory
from ..step import step
from .common import Driver

class Mode(enum.Enum):
    DD = ...
    BMAPTOOL = ...
    def __str__(self) -> str: ...

@target_factory.reg_driver
@attr.s(eq=False)
class USBStorageDriver(Driver):
    bindings = ...
    image = ...
    WAIT_FOR_MEDIUM_TIMEOUT = ...
    WAIT_FOR_MEDIUM_SLEEP = ...
    MOUNT_RETRIES = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
    @Driver.check_active
    @step(args=["sources", "target", "partition", "target_is_directory"])
    def write_files(
        self, sources, target, partition, target_is_directory=...
    ):  # -> None:
        """
        Write the file(s) specified by filename(s) to the
        bound USB storage partition.

        Args:
            sources (List[str]): path(s) to the file(s) to be copied to the bound USB storage
                partition.
            target (PurePath): target directory or file to copy to
            partition (int): mount the specified partition or None to mount the whole disk
            target_is_directory (bool): Whether target is a directory

        Raises:
            Exception if anything goes wrong
        """
        ...

    @Driver.check_active
    @step(args=["filename"])
    def write_image(
        self, filename=..., mode=..., partition=..., skip=..., seek=...
    ):  # -> None:
        """
        Writes the file specified by filename or if not specified by config image subkey to the
        bound USB storage root device or partition.

        Args:
            filename (str): optional, path to the image to write to bound USB storage
            mode (Mode): optional, Mode.DD or Mode.BMAPTOOL (defaults to Mode.DD)
            partition (int or None): optional, write to the specified partition or None for writing
                to root device (defaults to None)
            skip (int): optional, skip n 512-sized blocks at start of input file (defaults to 0)
            seek (int): optional, skip n 512-sized blocks at start of output (defaults to 0)
        """
        ...

    @Driver.check_active
    @step(args=["partition"], result=True)
    def get_size(self, partition=...):  # -> int:
        """
        Get the size of the bound USB storage root device or partition.

        Args:
            partition (int or None): optional, get size of the specified partition or None for
                getting the size of the root device (defaults to None)

        Returns:
            int: size in bytes, or 0 if the partition is not found
        """
        ...

@target_factory.reg_driver
@attr.s(eq=False)
class NetworkUSBStorageDriver(USBStorageDriver):
    def __attrs_post_init__(self):  # -> None:
        ...
