"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class USBTMCDriver(Driver):
    bindings = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def on_activate(self):  # -> None:
        ...
    def on_deactivate(self):  # -> None:
        ...
    @Driver.check_active
    def command(self, cmd):  # -> None:
        ...
    @Driver.check_active
    def query(self, cmd, binary=..., raw=...):  # -> bytes | str:
        ...
    @Driver.check_active
    def identify(self):  # -> bytes | str:
        ...
    @Driver.check_active
    def get_channel_info(self, channel):  # -> Any:
        ...
    @Driver.check_active
    def get_channel_values(self, channel):  # -> Any:
        ...
    @Driver.check_active
    def get_screenshot(
        self,
    ):  # -> tuple[Literal['png'], Any] | tuple[Literal['tiff'], Any]:
        ...
    @Driver.check_active
    def get_bool(self, cmd):  # -> bool:
        ...
    @Driver.check_active
    def get_int(self, cmd):  # -> int:
        ...
    @Driver.check_active
    def get_decimal(self, cmd):  # -> Decimal:
        ...
    @Driver.check_active
    def get_str(self, cmd):  # -> bytes | str:
        ...
