"""
This type stub file was generated by pyright.
"""

import attr

from ..factory import target_factory
from ..protocol import VideoProtocol
from .common import Driver

@target_factory.reg_driver
@attr.s(eq=False)
class USBVideoDriver(Driver, VideoProtocol):
    bindings = ...
    def __attrs_post_init__(self):  # -> None:
        ...
    def get_qualities(self):  # -> tuple[Literal['mid'], list[tuple[str, str]]]:
        ...
    def select_caps(self, hint=...):  # -> str:
        ...
    def get_pipeline(self, path, caps, controls=...):  # -> str:
        ...
    @Driver.check_active
    def stream(self, caps_hint=..., controls=...):  # -> None:
        ...
